export const FILTER_OPTIONS = {
  niveisEnsino: [
    "Ano Sabático",
    "Doutorado",
    "Ensino Médio",
    "Graduação",
    "MBA",
    "Mestrado",
    "Pós-Doutorado",
  ].sort(),

  tiposProgramaInternacional: [
    "Curso curta duração",
    "Curso de idiomas",
    "Curso de verão",
    "Doutorado",
    "Estágio/Trabalho",
    "Evento/Workshop",
    "Graduação",
    "High School",
    "Intercâmbio cultural",
    "MBA",
    "Mestrado",
    "Mobilidade acadêmica",
    "Pesquisa",
    "Trabalho voluntário",
  ].sort(),

  tiposProgramaNacional: [
    "Olimpíadas",
    "Feiras de Ciências",
    "Programas de Liderança",
    "Iniciação Científica",
    "Simulações da ONU",
    "Cursos & Imersões",
    "Programas de Mentoria",
    "Voluntariado/Social",
  ],

  paises: [
    "Adamar",
    "Alemanha",
    "Andorra",
    "Arábia Saudita",
    "Argentina",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahrein",
    "Bélgica",
    "Benin",
    "Botswana",
    "Brasil",
    "Bulgária",
    "Burkina Faso",
    "Cabo Verde",
    "Canadá",
    "Cazaquistão",
    "Chile",
    "China",
    "Chipre",
    "Colômbia",
    "Coreia do Sul",
    "Costa Rica",
    "Croácia",
    "Dinamarca",
    "Egito",
    "Emirados Árabes Unidos",
    "Eslováquia",
    "Espanha",
    "Estados Unidos",
    "Estonia",
    "Filipinas",
    "Finlândia",
    "França",
    "Gâmbia",
    "Gana",
    "Geórgia",
    "Grécia",
    "Guiné",
    "Hong Kong",
    "Hungria",
    "Índia",
    "Indonésia",
    "Inglaterra",
    "Irlanda",
    "Islândia",
    "Israel",
    "Itália",
    "Japão",
    "Jordânia",
    "Kuwait",
    "Líbano",
    "Lituânia",
    "Luxemburgo",
    "Madagascar",
    "Malásia",
    "Malta",
    "Marrocos",
    "México",
    "Mônaco",
    "Moçambique",
    "Namíbia",
    "Nigéria",
    "Noruega",
    "Nova Zelândia",
    "Omã",
    "Países Baixos",
    "Peru",
    "Polônia",
    "Portugal",
    "Qatar",
    "Reino Unido",
    "República Dominicana",
    "República Tcheca",
    "Romênia",
    "Ruanda",
    "Rússia",
    "San Marino",
    "Senegal",
    "Seychelles",
    "Singapura",
    "Somália",
    "Suécia",
    "Suíça",
    "Tailândia",
    "Tanzânia",
    "Togo",
    "Tunísia",
    "Turquia",
    "Ucrânia",
    "Uganda",
    "Vietnã",
    "Zâmbia",
  ].sort(),

  requisitosIdioma: [
    "Alemão",
    "Cantonês",
    "Espanhol",
    "Francês",
    "Holandês",
    "Inglês",
    "Italiano",
    "Japonês",
    "Mandarim",
    "Português",
  ].sort(),

  taxaAplicacao: ["Gratuito", "Pago"].sort(),

  tipoBolsa: ["Completa", "Parcial", "Sem bolsa"].sort(),

  modalidade: ["Presencial", "Online", "Híbrido"],
} as const
