export const universidades = [
  {
    "id": 1,
    "nome": "Massachusetts Institute of Technology",
    "sigla": "MIT",
    "estado": "MA",
    "cidade": "Cambridge",
    "setting": "urbano",
    "rankingNacional": "2",
    "taxaAceitacao": "5%",
    "faixaSAT": "1510-1580",
    "faixaACT": "34-36",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$100,000",
    "tuition": "$60,156",
    "roomBoard": "$17,170",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$55,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "4,576",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciência da Computação, Engenharia Mecânica, Matemática",
    "applicationFee": "$75",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@mit.edu"
  },
  {
    "id": 2,
    "nome": "Yale University",
    "sigla": "Yale",
    "estado": "CT",
    "cidade": "New Haven",
    "setting": "suburbano",
    "rankingNacional": "3",
    "taxaAceitacao": "5%",
    "faixaSAT": "1510-1580",
    "faixaACT": "34-36",
    "graduationRate4anos": "92%",
    "medianSalary6anos": "$85,000",
    "tuition": "$64,700",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$22,000",
    "averageNeedBasedAidPackage": "$60,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "6,590",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Ciências Sociais, História, Ciências Biológicas",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "undergraduate.admissions@yale.edu"
  },
  {
    "id": 3,
    "nome": "Stanford University",
    "sigla": "Stanford",
    "estado": "CA",
    "cidade": "Stanford",
    "setting": "suburbano",
    "rankingNacional": "1",
    "taxaAceitacao": "4%",
    "faixaSAT": "1510-1580",
    "faixaACT": "34-36",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$110,000",
    "tuition": "$62,484",
    "roomBoard": "$18,600",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$65,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "7,039",
    "percentualInternacionais": "13%",
    "majorsPrincipais": "Ciência da Computação, Engenharia, Ciências Humanas",
    "applicationFee": "$90",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Restrictive Early Action, Regular Decision",
    "contato": "admission@stanford.edu"
  },
  {
    "id": 4,
    "nome": "Harvard University",
    "sigla": "Harvard",
    "estado": "MA",
    "cidade": "Cambridge",
    "setting": "urbano",
    "rankingNacional": "3",
    "taxaAceitacao": "3%",
    "faixaSAT": "1520-1580",
    "faixaACT": "34-36",
    "graduationRate4anos": "94%",
    "medianSalary6anos": "$95,000",
    "tuition": "$59,076",
    "roomBoard": "$18,500",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$62,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,240",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Ciência da Computação, Economia, Ciências Políticas",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Restrictive Early Action, Regular Decision",
    "contato": "admissions@fas.harvard.edu"
  },
  {
    "id": 5,
    "nome": "Dartmouth College",
    "sigla": "Dartmouth",
    "estado": "NH",
    "cidade": "Hanover",
    "setting": "rural",
    "rankingNacional": "12",
    "taxaAceitacao": "6%",
    "faixaSAT": "1460-1560",
    "faixaACT": "33-35",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$88,000",
    "tuition": "$63,666",
    "roomBoard": "$16,900",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$58,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "4,458",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciências Sociais, Economia, Ciências Políticas",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions.office@dartmouth.edu"
  },
  {
    "id": 6,
    "nome": "Brown University",
    "sigla": "Brown",
    "estado": "RI",
    "cidade": "Providence",
    "setting": "urbano",
    "rankingNacional": "9",
    "taxaAceitacao": "5%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "91%",
    "medianSalary6anos": "$82,000",
    "tuition": "$68,612",
    "roomBoard": "$17,800",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$52,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "7,348",
    "percentualInternacionais": "16%",
    "majorsPrincipais": "Ciências Sociais, Biologia, Engenharia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admission@brown.edu"
  },
  {
    "id": 7,
    "nome": "Columbia University",
    "sigla": "Columbia",
    "estado": "NY",
    "cidade": "New York",
    "setting": "urbano",
    "rankingNacional": "7",
    "taxaAceitacao": "4%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "93%",
    "medianSalary6anos": "$90,000",
    "tuition": "$65,524",
    "roomBoard": "$19,500",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$60,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "9,055",
    "percentualInternacionais": "14%",
    "majorsPrincipais": "Ciências Sociais, Engenharia, Ciência da Computação",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "ugrad-ask@columbia.edu"
  },
  {
    "id": 8,
    "nome": "Rice University",
    "sigla": "Rice",
    "estado": "TX",
    "cidade": "Houston",
    "setting": "urbano",
    "rankingNacional": "17",
    "taxaAceitacao": "8%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$80,000",
    "tuition": "$60,252",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "4,249",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciência da Computação, Engenharia, Ciências Políticas",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admission@rice.edu"
  },
  {
    "id": 9,
    "nome": "Vanderbilt University",
    "sigla": "Vanderbilt",
    "estado": "TN",
    "cidade": "Nashville",
    "setting": "urbano",
    "rankingNacional": "13",
    "taxaAceitacao": "6%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "89%",
    "medianSalary6anos": "$83,000",
    "tuition": "$62,836",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$32,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "7,151",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Economia, Ciências Sociais, Enfermagem",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@vanderbilt.edu"
  },
  {
    "id": 10,
    "nome": "Princeton University",
    "sigla": "Princeton",
    "estado": "NJ",
    "cidade": "Princeton",
    "setting": "suburbano",
    "rankingNacional": "1",
    "taxaAceitacao": "4%",
    "faixaSAT": "1500-1580",
    "faixaACT": "34-36",
    "graduationRate4anos": "93%",
    "medianSalary6anos": "$98,000",
    "tuition": "$59,710",
    "roomBoard": "$18,000",
    "averageCostAfterAid": "$18,000",
    "averageNeedBasedAidPackage": "$65,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "5,590",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Engenharia, Ciências Sociais, Ciência da Computação",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Single-Choice Early Action, Regular Decision",
    "contato": "ua@princeton.edu"
  },
  {
    "id": 11,
    "nome": "University of Pennsylvania",
    "sigla": "Penn",
    "estado": "PA",
    "cidade": "Philadelphia",
    "setting": "urbano",
    "rankingNacional": "7",
    "taxaAceitacao": "6%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "91%",
    "medianSalary6anos": "$92,000",
    "tuition": "$62,774",
    "roomBoard": "$18,200",
    "averageCostAfterAid": "$29,000",
    "averageNeedBasedAidPackage": "$55,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "10,019",
    "percentualInternacionais": "14%",
    "majorsPrincipais": "Ciências Sociais, Finanças, Economia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "info@admissions.upenn.edu"
  },
  {
    "id": 12,
    "nome": "Duke University",
    "sigla": "Duke",
    "estado": "NC",
    "cidade": "Durham",
    "setting": "suburbano",
    "rankingNacional": "10",
    "taxaAceitacao": "7%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "91%",
    "medianSalary6anos": "$85,000",
    "tuition": "$64,550",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$53,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "6,789",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciência da Computação, Economia, Políticas Governamentais",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "undergrad-admissions@duke.edu"
  },
  {
    "id": 13,
    "nome": "Georgetown University",
    "sigla": "Georgetown",
    "estado": "DC",
    "cidade": "Washington",
    "setting": "urbano",
    "rankingNacional": "22",
    "taxaAceitacao": "13%",
    "faixaSAT": "1450-1560",
    "faixaACT": "33-35",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$90,000",
    "tuition": "$62,334",
    "roomBoard": "$17,200",
    "averageCostAfterAid": "$38,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,357",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciências Políticas, Finanças, Economia",
    "applicationFee": "$75",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "guadmiss@georgetown.edu"
  },
  {
    "id": 14,
    "nome": "Harvey Mudd College",
    "sigla": "HMC",
    "estado": "CA",
    "cidade": "Claremont",
    "setting": "suburbano",
    "rankingNacional": "14",
    "taxaAceitacao": "13%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-35",
    "graduationRate4anos": "87%",
    "medianSalary6anos": "$115,000",
    "tuition": "$67,288",
    "roomBoard": "$18,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$48,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "936",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Engenharia, Ciência da Computação, Matemática",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@hmc.edu"
  },
  {
    "id": 15,
    "nome": "Pomona College",
    "sigla": "Pomona",
    "estado": "CA",
    "cidade": "Claremont",
    "setting": "suburbano",
    "rankingNacional": "4",
    "taxaAceitacao": "7%",
    "faixaSAT": "1460-1560",
    "faixaACT": "33-35",
    "graduationRate4anos": "91%",
    "medianSalary6anos": "$75,000",
    "tuition": "$64,717",
    "roomBoard": "$17,200",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$55,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,745",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciências Sociais, Economia, Ciências Biológicas",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@pomona.edu"
  },
  {
    "id": 16,
    "nome": "Northwestern University",
    "sigla": "Northwestern",
    "estado": "IL",
    "cidade": "Evanston",
    "setting": "suburbano",
    "rankingNacional": "9",
    "taxaAceitacao": "7%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$87,000",
    "tuition": "$64,089",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "8,435",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Jornalismo, Economia, Psicologia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "ug-admission@northwestern.edu"
  },
  {
    "id": 17,
    "nome": "Carnegie Mellon University",
    "sigla": "CMU",
    "estado": "PA",
    "cidade": "Pittsburgh",
    "setting": "urbano",
    "rankingNacional": "17",
    "taxaAceitacao": "11%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "86%",
    "medianSalary6anos": "$95,000",
    "tuition": "$64,596",
    "roomBoard": "$17,800",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,073",
    "percentualInternacionais": "18%",
    "majorsPrincipais": "Engenharia, Ciência da Computação, Música",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admission@andrew.cmu.edu"
  },
  {
    "id": 18,
    "nome": "Cornell University",
    "sigla": "Cornell",
    "estado": "NY",
    "cidade": "Ithaca",
    "setting": "suburbano",
    "rankingNacional": "12",
    "taxaAceitacao": "7%",
    "faixaSAT": "1470-1550",
    "faixaACT": "33-35",
    "graduationRate4anos": "89%",
    "medianSalary6anos": "$84,000",
    "tuition": "$67,876",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$48,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "15,343",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Engenharia, Ciências da Comunicação, Biologia",
    "applicationFee": "$80",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@cornell.edu"
  },
  {
    "id": 19,
    "nome": "Johns Hopkins University",
    "sigla": "JHU",
    "estado": "MD",
    "cidade": "Baltimore",
    "setting": "urbano",
    "rankingNacional": "9",
    "taxaAceitacao": "7%",
    "faixaSAT": "1500-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "89%",
    "medianSalary6anos": "$85,000",
    "tuition": "$62,900",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$33,000",
    "averageNeedBasedAidPackage": "$48,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "6,357",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Ciências Biológicas, Saúde Pública, Engenharia",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "gotojhu@jhu.edu"
  },
  {
    "id": 20,
    "nome": "University of Michigan - Ann Arbor",
    "sigla": "U-M",
    "estado": "MI",
    "cidade": "Ann Arbor",
    "setting": "urbano",
    "rankingNacional": "21",
    "taxaAceitacao": "26%",
    "faixaSAT": "1360-1540",
    "faixaACT": "31-34",
    "graduationRate4anos": "84%",
    "medianSalary6anos": "$78,000",
    "tuition": "$52,924",
    "roomBoard": "$15,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$30,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "32,695",
    "percentualInternacionais": "9%",
    "majorsPrincipais": "Ciências da Computação, Economia, Ciências Políticas",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "ugadmiss@umich.edu"
  },
  {
    "id": 21,
    "nome": "University of Chicago",
    "sigla": "UChicago",
    "estado": "IL",
    "cidade": "Chicago",
    "setting": "urbano",
    "rankingNacional": "6",
    "taxaAceitacao": "6%",
    "faixaSAT": "1520-1570",
    "faixaACT": "34-36",
    "graduationRate4anos": "92%",
    "medianSalary6anos": "$88,000",
    "tuition": "$65,748",
    "roomBoard": "$18,500",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$55,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,397",
    "percentualInternacionais": "14%",
    "majorsPrincipais": "Ciências Políticas, Economia, Matemática",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Early Decision I & II, Regular Decision",
    "contato": "collegeadmissions@uchicago.edu"
  },
  {
    "id": 22,
    "nome": "University of Southern California",
    "sigla": "USC",
    "estado": "CA",
    "cidade": "Los Angeles",
    "setting": "urbano",
    "rankingNacional": "28",
    "taxaAceitacao": "12%",
    "faixaSAT": "1440-1550",
    "faixaACT": "33-35",
    "graduationRate4anos": "86%",
    "medianSalary6anos": "$80,000",
    "tuition": "$68,790",
    "roomBoard": "$18,000",
    "averageCostAfterAid": "$38,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "21,050",
    "percentualInternacionais": "18%",
    "majorsPrincipais": "Negócios, Ciências Políticas, Cinema",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "adm@usc.edu"
  },
  {
    "id": 23,
    "nome": "Georgia Institute of Technology",
    "sigla": "Georgia Tech",
    "estado": "GA",
    "cidade": "Atlanta",
    "setting": "urbano",
    "rankingNacional": "44",
    "taxaAceitacao": "17%",
    "faixaSAT": "1400-1550",
    "faixaACT": "32-35",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$90,000",
    "tuition": "$33,794",
    "roomBoard": "$15,000",
    "averageCostAfterAid": "$22,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "17,433",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Ciência da Computação, Engenharia, Administração de Empresas",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admission@gatech.edu"
  },
  {
    "id": 24,
    "nome": "Swarthmore College",
    "sigla": "Swarthmore",
    "estado": "PA",
    "cidade": "Swarthmore",
    "setting": "suburbano",
    "rankingNacional": "3",
    "taxaAceitacao": "7%",
    "faixaSAT": "1470-1570",
    "faixaACT": "33-35",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$70,000",
    "tuition": "$62,720",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,624",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciências Sociais, Biologia, Inglês",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@swarthmore.edu"
  },
  {
    "id": 25,
    "nome": "Emory University",
    "sigla": "Emory",
    "estado": "GA",
    "cidade": "Atlanta",
    "setting": "urbano",
    "rankingNacional": "24",
    "taxaAceitacao": "13%",
    "faixaSAT": "1470-1560",
    "faixaACT": "33-35",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$75,000",
    "tuition": "$62,246",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$38,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,079",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciências Sociais, Finanças, Biologia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@emory.edu"
  },
  {
    "id": 26,
    "nome": "University of North Carolina at Chapel Hill",
    "sigla": "UNC",
    "estado": "NC",
    "cidade": "Chapel Hill",
    "setting": "suburbano",
    "rankingNacional": "29",
    "taxaAceitacao": "17%",
    "faixaSAT": "1390-1530",
    "faixaACT": "31-34",
    "graduationRate4anos": "86%",
    "medianSalary6anos": "$70,000",
    "tuition": "$36,891",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "20,730",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Ciências da Comunicação, Biologia, Psicologia",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "unchelp@admissions.unc.edu"
  },
  {
    "id": 27,
    "nome": "University of California - Los Angeles",
    "sigla": "UCLA",
    "estado": "CA",
    "cidade": "Los Angeles",
    "setting": "urbano",
    "rankingNacional": "19",
    "taxaAceitacao": "9%",
    "faixaSAT": "1390-1540",
    "faixaACT": "31-34",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$78,000",
    "tuition": "$46,326",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$32,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "32,423",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Ciências Sociais, Biologia, Psicologia",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "ugadm@admissions.ucla.edu"
  },
  {
    "id": 28,
    "nome": "Claremont McKenna College",
    "sigla": "CMC",
    "estado": "CA",
    "cidade": "Claremont",
    "setting": "suburbano",
    "rankingNacional": "8",
    "taxaAceitacao": "9%",
    "faixaSAT": "1450-1550",
    "faixaACT": "33-35",
    "graduationRate4anos": "92%",
    "medianSalary6anos": "$85,000",
    "tuition": "$68,612",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,341",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciências Políticas, Economia, Finanças",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@cmc.edu"
  },
  {
    "id": 29,
    "nome": "Barnard College",
    "sigla": "Barnard",
    "estado": "NY",
    "cidade": "New York",
    "setting": "urbano",
    "rankingNacional": "12",
    "taxaAceitacao": "8%",
    "faixaSAT": "1450-1550",
    "faixaACT": "32-34",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$70,000",
    "tuition": "$95,700",
    "roomBoard": "$18,500",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "3,353",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Economia, Psicologia, Ciência Política",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@barnard.edu"
  },
  {
    "id": 30,
    "nome": "Boston University",
    "sigla": "BU",
    "estado": "MA",
    "cidade": "Boston",
    "setting": "urbano",
    "rankingNacional": "43",
    "taxaAceitacao": "14%",
    "faixaSAT": "1380-1530",
    "faixaACT": "31-34",
    "graduationRate4anos": "86%",
    "medianSalary6anos": "$70,000",
    "tuition": "$88,582",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$50,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "18,514",
    "percentualInternacionais": "17%",
    "majorsPrincipais": "Administração de Empresas, Finanças, Psicologia",
    "applicationFee": "$80",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@bu.edu"
  },
  {
    "id": 31,
    "nome": "New York University",
    "sigla": "NYU",
    "estado": "NY",
    "cidade": "New York",
    "setting": "urbano",
    "rankingNacional": "35",
    "taxaAceitacao": "12%",
    "faixaSAT": "1460-1570",
    "faixaACT": "32-35",
    "graduationRate4anos": "84%",
    "medianSalary6anos": "$75,000",
    "tuition": "$90,582",
    "roomBoard": "$18,000",
    "averageCostAfterAid": "$55,000",
    "averageNeedBasedAidPackage": "$35,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "26,657",
    "percentualInternacionais": "22%",
    "majorsPrincipais": "Finanças, Marketing, Economia",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@nyu.edu"
  },
  {
    "id": 32,
    "nome": "Northeastern University",
    "sigla": "Northeastern",
    "estado": "MA",
    "cidade": "Boston",
    "setting": "urbano",
    "rankingNacional": "49",
    "taxaAceitacao": "7%",
    "faixaSAT": "1440-1550",
    "faixaACT": "33-35",
    "graduationRate4anos": "80%",
    "medianSalary6anos": "$80,000",
    "tuition": "$86,300",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$48,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "16,846",
    "percentualInternacionais": "20%",
    "majorsPrincipais": "Administração de Empresas, Finanças, Tecnologia da Informação",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Early Action, Regular Decision",
    "contato": "admissions@northeastern.edu"
  },
  {
    "id": 33,
    "nome": "University of California - Berkeley",
    "sigla": "UC Berkeley",
    "estado": "CA",
    "cidade": "Berkeley",
    "setting": "urbano",
    "rankingNacional": "19",
    "taxaAceitacao": "15%",
    "faixaSAT": "1330-1530",
    "faixaACT": "31-35",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$85,000",
    "tuition": "$46,300",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$30,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "30,799",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciências da Computação, Economia, Psicologia",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "ask@berkeley.edu"
  },
  {
    "id": 34,
    "nome": "Wellesley College",
    "sigla": "Wellesley",
    "estado": "MA",
    "cidade": "Wellesley",
    "setting": "suburbano",
    "rankingNacional": "5",
    "taxaAceitacao": "13%",
    "faixaSAT": "1400-1530",
    "faixaACT": "32-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$65,000",
    "tuition": "$87,896",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,423",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Economia, Ciência Política, Psicologia",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@wellesley.edu"
  },
  {
    "id": 35,
    "nome": "University of Texas - Austin",
    "sigla": "UT Austin",
    "estado": "TX",
    "cidade": "Austin",
    "setting": "urbano",
    "rankingNacional": "32",
    "taxaAceitacao": "31%",
    "faixaSAT": "1260-1490",
    "faixaACT": "29-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$75,000",
    "tuition": "$43,900",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "40,804",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Ciência da Computação, Economia, Finanças",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Priority, Regular Decision",
    "contato": "admissions@utexas.edu"
  },
  {
    "id": 36,
    "nome": "Middlebury College",
    "sigla": "Middlebury",
    "estado": "VT",
    "cidade": "Middlebury",
    "setting": "rural",
    "rankingNacional": "10",
    "taxaAceitacao": "16%",
    "faixaSAT": "1370-1520",
    "faixaACT": "31-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$60,000",
    "tuition": "$85,600",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$42,000",
    "averageNeedBasedAidPackage": "$48,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,879",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Ciências do Meio Ambiente, Economia, Ciência Política",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@middlebury.edu"
  },
  {
    "id": 37,
    "nome": "Tufts University",
    "sigla": "Tufts",
    "estado": "MA",
    "cidade": "Medford",
    "setting": "suburbano",
    "rankingNacional": "28",
    "taxaAceitacao": "9%",
    "faixaSAT": "1460-1550",
    "faixaACT": "33-35",
    "graduationRate4anos": "87%",
    "medianSalary6anos": "$78,000",
    "tuition": "$86,832",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$42,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "6,702",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Ciência da Computação, Ciências do Meio Ambiente, Economia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "undergraduate.admissions@tufts.edu"
  },
  {
    "id": 38,
    "nome": "Amherst College",
    "sigla": "Amherst",
    "estado": "MA",
    "cidade": "Amherst",
    "setting": "suburbano",
    "rankingNacional": "2",
    "taxaAceitacao": "9%",
    "faixaSAT": "1440-1550",
    "faixaACT": "32-35",
    "graduationRate4anos": "91%",
    "medianSalary6anos": "$75,000",
    "tuition": "$86,582",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,898",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Economia, Ciência Política, Inglês",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admission@amherst.edu"
  },
  {
    "id": 39,
    "nome": "University of Illinois Urbana-Champaign",
    "sigla": "UIUC",
    "estado": "IL",
    "cidade": "Urbana",
    "setting": "urbano",
    "rankingNacional": "38",
    "taxaAceitacao": "45%",
    "faixaSAT": "1340-1530",
    "faixaACT": "29-34",
    "graduationRate4anos": "79%",
    "medianSalary6anos": "$70,000",
    "tuition": "$50,320",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "33,729",
    "percentualInternacionais": "14%",
    "majorsPrincipais": "Ciências da Computação, Administração de Empresas, Economia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@illinois.edu"
  },
  {
    "id": 40,
    "nome": "University of Miami",
    "sigla": "UM",
    "estado": "FL",
    "cidade": "Coral Gables",
    "setting": "suburbano",
    "rankingNacional": "67",
    "taxaAceitacao": "19%",
    "faixaSAT": "1330-1490",
    "faixaACT": "30-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$65,000",
    "tuition": "$85,744",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$50,000",
    "averageNeedBasedAidPackage": "$30,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "11,272",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Finanças, Marketing, Biologia",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Early Action, Regular Decision",
    "contato": "admission@miami.edu"
  },
  {
    "id": 41,
    "nome": "University of Wisconsin-Madison",
    "sigla": "UW-Madison",
    "estado": "WI",
    "cidade": "Madison",
    "setting": "urbano",
    "rankingNacional": "35",
    "taxaAceitacao": "50%",
    "faixaSAT": "1330-1500",
    "faixaACT": "28-32",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$68,000",
    "tuition": "$45,862",
    "roomBoard": "$13,500",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "35,834",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Ciências da Computação, Economia, Finanças",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@wisc.edu"
  },
  {
    "id": 42,
    "nome": "Haverford College",
    "sigla": "Haverford",
    "estado": "PA",
    "cidade": "Haverford",
    "setting": "suburbano",
    "rankingNacional": "18",
    "taxaAceitacao": "18%",
    "faixaSAT": "1390-1530",
    "faixaACT": "32-35",
    "graduationRate4anos": "92%",
    "medianSalary6anos": "$70,000",
    "tuition": "$85,600",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,341",
    "percentualInternacionais": "9%",
    "majorsPrincipais": "Ciências da Computação, Ciências do Meio Ambiente, Economia",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@haverford.edu"
  },
  {
    "id": 43,
    "nome": "Virginia Tech",
    "sigla": "VT",
    "estado": "VA",
    "cidade": "Blacksburg",
    "setting": "suburbano",
    "rankingNacional": "47",
    "taxaAceitacao": "64%",
    "faixaSAT": "1250-1420",
    "faixaACT": "27-32",
    "graduationRate4anos": "70%",
    "medianSalary6anos": "$70,000",
    "tuition": "$41,073",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "30,810",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Tecnologia da Informação",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "vtadmiss@vt.edu"
  },
  {
    "id": 44,
    "nome": "University of Washington",
    "sigla": "UW",
    "estado": "WA",
    "cidade": "Seattle",
    "setting": "urbano",
    "rankingNacional": "40",
    "taxaAceitacao": "46%",
    "faixaSAT": "1240-1490",
    "faixaACT": "28-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$75,000",
    "tuition": "$41,010",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "32,062",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciência da Computação, Administração de Empresas, Economia",
    "applicationFee": "$85",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "askuwadm@uw.edu"
  },
  {
    "id": 45,
    "nome": "University of California - Davis",
    "sigla": "UC Davis",
    "estado": "CA",
    "cidade": "Davis",
    "setting": "suburbano",
    "rankingNacional": "38",
    "taxaAceitacao": "42%",
    "faixaSAT": "1190-1430",
    "faixaACT": "26-33",
    "graduationRate4anos": "75%",
    "medianSalary6anos": "$65,000",
    "tuition": "$46,396",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "31,066",
    "percentualInternacionais": "9%",
    "majorsPrincipais": "Ciência da Computação, Economia, Psicologia",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "undergrad@ucdavis.edu"
  },
  {
    "id": 46,
    "nome": "Wesleyan University",
    "sigla": "Wesleyan",
    "estado": "CT",
    "cidade": "Middletown",
    "setting": "urbano",
    "rankingNacional": "17",
    "taxaAceitacao": "14%",
    "faixaSAT": "1430-1550",
    "faixaACT": "32-35",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$70,000",
    "tuition": "$88,090",
    "roomBoard": "$17,500",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$48,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,987",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciências Sociais, Estudos de Cinema, Artes",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@wesleyan.edu"
  },
  {
    "id": 47,
    "nome": "The Cooper Union for the Advancement of Science and Art",
    "sigla": "Cooper Union",
    "estado": "NY",
    "cidade": "New York",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "15%",
    "faixaSAT": "1370-1530",
    "faixaACT": "30-34",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$80,000",
    "tuition": "$51,040",
    "roomBoard": "$18,500",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "863",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Engenharia, Arquitetura, Arte",
    "applicationFee": "$100",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@cooper.edu"
  },
  {
    "id": 48,
    "nome": "Purdue University",
    "sigla": "Purdue",
    "estado": "IN",
    "cidade": "West Lafayette",
    "setting": "suburbano",
    "rankingNacional": "51",
    "taxaAceitacao": "52%",
    "faixaSAT": "1210-1430",
    "faixaACT": "27-33",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$68,000",
    "tuition": "$44,382",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$22,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "38,749",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Engenharia, Administração de Empresas, Ciência da Computação",
    "applicationFee": "$75",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@purdue.edu"
  },
  {
    "id": 49,
    "nome": "University of South Florida",
    "sigla": "USF",
    "estado": "FL",
    "cidade": "Tampa",
    "setting": "urbano",
    "rankingNacional": "89",
    "taxaAceitacao": "41%",
    "faixaSAT": "1180-1340",
    "faixaACT": "25-30",
    "graduationRate4anos": "55%",
    "medianSalary6anos": "$55,000",
    "tuition": "$22,254",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "38,384",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Finanças, Enfermagem, Administração de Empresas",
    "applicationFee": "$30",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@usf.edu"
  },
  {
    "id": 50,
    "nome": "University of Richmond",
    "sigla": "UR",
    "estado": "VA",
    "cidade": "Richmond",
    "setting": "suburbano",
    "rankingNacional": "22",
    "taxaAceitacao": "24%",
    "faixaSAT": "1380-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$70,000",
    "tuition": "$82,160",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "3,176",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Economia",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@richmond.edu"
  },
  {
    "id": 51,
    "nome": "University of Maryland - College Park",
    "sigla": "UMD",
    "estado": "MD",
    "cidade": "College Park",
    "setting": "suburbano",
    "rankingNacional": "46",
    "taxaAceitacao": "41%",
    "faixaSAT": "1370-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$70,000",
    "tuition": "$52,793",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "30,762",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Ciência da Computação, Administração de Empresas, Economia",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "um-admit@umd.edu"
  },
  {
    "id": 52,
    "nome": "Colby College",
    "sigla": "Colby",
    "estado": "ME",
    "cidade": "Waterville",
    "setting": "suburbano",
    "rankingNacional": "18",
    "taxaAceitacao": "8%",
    "faixaSAT": "1420-1530",
    "faixaACT": "32-34",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$65,000",
    "tuition": "$85,340",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$50,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,302",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Economia, Ciência Política, Biologia",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@colby.edu"
  },
  {
    "id": 53,
    "nome": "The Ohio State University",
    "sigla": "OSU",
    "estado": "OH",
    "cidade": "Columbus",
    "setting": "urbano",
    "rankingNacional": "43",
    "taxaAceitacao": "53%",
    "faixaSAT": "1270-1460",
    "faixaACT": "27-32",
    "graduationRate4anos": "68%",
    "medianSalary6anos": "$60,000",
    "tuition": "$45,696",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$18,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "46,829",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Finanças, Psicologia, Enfermagem",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "undergrad@osu.edu"
  },
  {
    "id": 54,
    "nome": "Case Western Reserve University",
    "sigla": "Case Western",
    "estado": "OH",
    "cidade": "Cleveland",
    "setting": "urbano",
    "rankingNacional": "49",
    "taxaAceitacao": "27%",
    "faixaSAT": "1420-1530",
    "faixaACT": "32-35",
    "graduationRate4anos": "80%",
    "medianSalary6anos": "$75,000",
    "tuition": "$85,498",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "6,136",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Biologia, Ciência da Computação, Engenharia Mecânica",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@case.edu"
  },
  {
    "id": 55,
    "nome": "University of California - Santa Barbara",
    "sigla": "UC Santa Barbara",
    "estado": "CA",
    "cidade": "Santa Barbara",
    "setting": "suburbano",
    "rankingNacional": "28",
    "taxaAceitacao": "26%",
    "faixaSAT": "1270-1490",
    "faixaACT": "28-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$68,000",
    "tuition": "$46,396",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "23,196",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Economia, Psicologia, Sociologia",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@ucsb.edu"
  },
  {
    "id": 56,
    "nome": "University of Central Florida",
    "sigla": "UCF",
    "estado": "FL",
    "cidade": "Orlando",
    "setting": "suburbano",
    "rankingNacional": "137",
    "taxaAceitacao": "41%",
    "faixaSAT": "1160-1360",
    "faixaACT": "25-30",
    "graduationRate4anos": "55%",
    "medianSalary6anos": "$52,000",
    "tuition": "$22,454",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "58,756",
    "percentualInternacionais": "5%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Psicologia",
    "applicationFee": "$30",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admission@ucf.edu"
  },
  {
    "id": 57,
    "nome": "Babson College",
    "sigla": "Babson",
    "estado": "MA",
    "cidade": "Wellesley",
    "setting": "suburbano",
    "rankingNacional": "1",
    "taxaAceitacao": "22%",
    "faixaSAT": "1370-1500",
    "faixaACT": "31-34",
    "graduationRate4anos": "90%",
    "medianSalary6anos": "$85,000",
    "tuition": "$85,198",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,450",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Finanças, Empreendedorismo, Negócios",
    "applicationFee": "$75",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Early Action, Regular Decision",
    "contato": "ugradadmission@babson.edu"
  },
  {
    "id": 58,
    "nome": "Indiana University - Bloomington",
    "sigla": "IU",
    "estado": "IN",
    "cidade": "Bloomington",
    "setting": "suburbano",
    "rankingNacional": "72",
    "taxaAceitacao": "82%",
    "faixaSAT": "1210-1420",
    "faixaACT": "26-32",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$60,000",
    "tuition": "$45,642",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "38,358",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Administração de Empresas, Ciência Política, Jornalismo",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "iuadmit@indiana.edu"
  },
  {
    "id": 59,
    "nome": "Florida International University",
    "sigla": "FIU",
    "estado": "FL",
    "cidade": "Miami",
    "setting": "urbano",
    "rankingNacional": "124",
    "taxaAceitacao": "59%",
    "faixaSAT": "1120-1280",
    "faixaACT": "23-28",
    "graduationRate4anos": "50%",
    "medianSalary6anos": "$50,000",
    "tuition": "$22,583",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "41,517",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Psicologia, Biologia, Criminologia",
    "applicationFee": "$30",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admiss@fiu.edu"
  },
  {
    "id": 60,
    "nome": "Macalester College",
    "sigla": "Macalester",
    "estado": "MN",
    "cidade": "Saint Paul",
    "setting": "urbano",
    "rankingNacional": "26",
    "taxaAceitacao": "27%",
    "faixaSAT": "1370-1500",
    "faixaACT": "31-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$60,000",
    "tuition": "$83,696",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,148",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Ciências Sociais, Economia, Ciência Política",
    "applicationFee": "$40",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@macalester.edu"
  },
  {
    "id": 61,
    "nome": "Grinnell College",
    "sigla": "Grinnell",
    "estado": "IA",
    "cidade": "Grinnell",
    "setting": "rural",
    "rankingNacional": "13",
    "taxaAceitacao": "11%",
    "faixaSAT": "1390-1530",
    "faixaACT": "31-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$65,000",
    "tuition": "$80,200",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$35,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,761",
    "percentualInternacionais": "14%",
    "majorsPrincipais": "Ciência Política, Economia, Matemática",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "ask@grinnell.edu"
  },
  {
    "id": 62,
    "nome": "University of Rochester",
    "sigla": "U of R",
    "estado": "NY",
    "cidade": "Rochester",
    "setting": "urbano",
    "rankingNacional": "36",
    "taxaAceitacao": "39%",
    "faixaSAT": "1370-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "80%",
    "medianSalary6anos": "$70,000",
    "tuition": "$85,760",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "6,559",
    "percentualInternacionais": "17%",
    "majorsPrincipais": "Biologia, Economia, Ciência Política",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@rochester.edu"
  },
  {
    "id": 63,
    "nome": "Arizona State University",
    "sigla": "ASU",
    "estado": "AZ",
    "cidade": "Tempe",
    "setting": "urbano",
    "rankingNacional": "105",
    "taxaAceitacao": "88%",
    "faixaSAT": "1140-1380",
    "faixaACT": "22-29",
    "graduationRate4anos": "55%",
    "medianSalary6anos": "$55,000",
    "tuition": "$40,595",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$12,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "63,666",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Comunicação",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admission@asu.edu"
  },
  {
    "id": 64,
    "nome": "University of Massachusetts Amherst",
    "sigla": "UMass Amherst",
    "estado": "MA",
    "cidade": "Amherst",
    "setting": "suburbano",
    "rankingNacional": "67",
    "taxaAceitacao": "64%",
    "faixaSAT": "1260-1430",
    "faixaACT": "27-32",
    "graduationRate4anos": "68%",
    "medianSalary6anos": "$60,000",
    "tuition": "$45,656",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "23,329",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Administração de Empresas, Psicologia, Economia",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "mail@admissions.umass.edu"
  },
  {
    "id": 65,
    "nome": "Michigan State University",
    "sigla": "MSU",
    "estado": "MI",
    "cidade": "East Lansing",
    "setting": "urbano",
    "rankingNacional": "72",
    "taxaAceitacao": "88%",
    "faixaSAT": "1120-1330",
    "faixaACT": "23-29",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$60,000",
    "tuition": "$46,438",
    "roomBoard": "$12,500",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "40,528",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Comunicação",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@msu.edu"
  },
  {
    "id": 66,
    "nome": "University of Minnesota Twin Cities",
    "sigla": "UMN",
    "estado": "MN",
    "cidade": "Minneapolis",
    "setting": "urbano",
    "rankingNacional": "62",
    "taxaAceitacao": "75%",
    "faixaSAT": "1290-1500",
    "faixaACT": "27-32",
    "graduationRate4anos": "67%",
    "medianSalary6anos": "$65,000",
    "tuition": "$39,544",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "35,803",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Ciência da Computação, Psicologia, Biologia",
    "applicationFee": "$55",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@umn.edu"
  },
  {
    "id": 67,
    "nome": "Smith College",
    "sigla": "Smith",
    "estado": "MA",
    "cidade": "Northampton",
    "setting": "suburbano",
    "rankingNacional": "18",
    "taxaAceitacao": "20%",
    "faixaSAT": "1360-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$60,000",
    "tuition": "$84,776",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$38,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,455",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Ciência Política, Economia, Inglês",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@smith.edu"
  },
  {
    "id": 68,
    "nome": "University of Utah",
    "sigla": "U of U",
    "estado": "UT",
    "cidade": "Salt Lake City",
    "setting": "urbano",
    "rankingNacional": "115",
    "taxaAceitacao": "82%",
    "faixaSAT": "1150-1390",
    "faixaACT": "23-30",
    "graduationRate4anos": "58%",
    "medianSalary6anos": "$55,000",
    "tuition": "$35,088",
    "roomBoard": "$11,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "26,657",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Psicologia",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@utah.edu"
  },
  {
    "id": 69,
    "nome": "Penn State",
    "sigla": "PSU",
    "estado": "PA",
    "cidade": "University Park",
    "setting": "suburbano",
    "rankingNacional": "60",
    "taxaAceitacao": "59%",
    "faixaSAT": "1210-1410",
    "faixaACT": "27-32",
    "graduationRate4anos": "68%",
    "medianSalary6anos": "$65,000",
    "tuition": "$49,020",
    "roomBoard": "$13,500",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$18,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "40,540",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Administração de Empresas, Finanças, Ciência da Computação",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@psu.edu"
  },
  {
    "id": 70,
    "nome": "Rutgers University–New Brunswick",
    "sigla": "Rutgers",
    "estado": "NJ",
    "cidade": "New Brunswick",
    "setting": "urbano",
    "rankingNacional": "40",
    "taxaAceitacao": "66%",
    "faixaSAT": "1210-1430",
    "faixaACT": "27-33",
    "graduationRate4anos": "72%",
    "medianSalary6anos": "$68,000",
    "tuition": "$35,631",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$22,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "35,807",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Administração de Empresas, Psicologia, Ciência da Computação",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@rutgers.edu"
  },
  {
    "id": 71,
    "nome": "University of Arizona",
    "sigla": "UArizona",
    "estado": "AZ",
    "cidade": "Tucson",
    "setting": "urbano",
    "rankingNacional": "105",
    "taxaAceitacao": "88%",
    "faixaSAT": "1140-1380",
    "faixaACT": "22-29",
    "graduationRate4anos": "58%",
    "medianSalary6anos": "$52,000",
    "tuition": "$41,802",
    "roomBoard": "$12,500",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$12,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "35,803",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Comunicação",
    "applicationFee": "$70",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@arizona.edu"
  },
  {
    "id": 72,
    "nome": "Mount Holyoke College",
    "sigla": "Mount Holyoke",
    "estado": "MA",
    "cidade": "South Hadley",
    "setting": "suburbano",
    "rankingNacional": "32",
    "taxaAceitacao": "37%",
    "faixaSAT": "1330-1510",
    "faixaACT": "30-34",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$60,000",
    "tuition": "$83,696",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,222",
    "percentualInternacionais": "18%",
    "majorsPrincipais": "Biologia, Ciência Política, Economia",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admission@mtholyoke.edu"
  },
  {
    "id": 73,
    "nome": "University of Connecticut",
    "sigla": "UConn",
    "estado": "CT",
    "cidade": "Storrs",
    "setting": "suburbano",
    "rankingNacional": "67",
    "taxaAceitacao": "51%",
    "faixaSAT": "1230-1430",
    "faixaACT": "27-32",
    "graduationRate4anos": "70%",
    "medianSalary6anos": "$65,000",
    "tuition": "$46,592",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$28,000",
    "averageNeedBasedAidPackage": "$22,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "19,324",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Finanças, Psicologia, Economia",
    "applicationFee": "$80",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "beahusky@uconn.edu"
  },
  {
    "id": 74,
    "nome": "Brandeis University",
    "sigla": "Brandeis",
    "estado": "MA",
    "cidade": "Waltham",
    "setting": "suburbano",
    "rankingNacional": "49",
    "taxaAceitacao": "39%",
    "faixaSAT": "1350-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "80%",
    "medianSalary6anos": "$70,000",
    "tuition": "$85,600",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "3,633",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Biologia, Economia, Ciência Política",
    "applicationFee": "$80",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@brandeis.edu"
  },
  {
    "id": 75,
    "nome": "Trinity College",
    "sigla": "Trinity",
    "estado": "CT",
    "cidade": "Hartford",
    "setting": "urbano",
    "rankingNacional": "32",
    "taxaAceitacao": "38%",
    "faixaSAT": "1310-1460",
    "faixaACT": "29-33",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$65,000",
    "tuition": "$86,582",
    "roomBoard": "$16,500",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$42,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,138",
    "percentualInternacionais": "9%",
    "majorsPrincipais": "Economia, Ciência Política, Inglês",
    "applicationFee": "$65",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@trincoll.edu"
  },
  {
    "id": 76,
    "nome": "Kenyon College",
    "sigla": "Kenyon",
    "estado": "OH",
    "cidade": "Gambier",
    "setting": "rural",
    "rankingNacional": "32",
    "taxaAceitacao": "30%",
    "faixaSAT": "1340-1500",
    "faixaACT": "30-34",
    "graduationRate4anos": "87%",
    "medianSalary6anos": "$60,000",
    "tuition": "$81,710",
    "roomBoard": "$15,500",
    "averageCostAfterAid": "$38,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,761",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Inglês, Ciência Política, Economia",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@kenyon.edu"
  },
  {
    "id": 77,
    "nome": "Bryn Mawr College",
    "sigla": "Bryn Mawr",
    "estado": "PA",
    "cidade": "Bryn Mawr",
    "setting": "suburbano",
    "rankingNacional": "32",
    "taxaAceitacao": "27%",
    "faixaSAT": "1370-1510",
    "faixaACT": "31-34",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$65,000",
    "tuition": "$86,300",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$45,000",
    "politicaFinanceira": "need-blind",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "1,705",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Ciências Sociais, Biologia, Inglês",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@brynmawr.edu"
  },
  {
    "id": 78,
    "nome": "Drexel University",
    "sigla": "Drexel",
    "estado": "PA",
    "cidade": "Philadelphia",
    "setting": "urbano",
    "rankingNacional": "105",
    "taxaAceitacao": "77%",
    "faixaSAT": "1240-1420",
    "faixaACT": "27-32",
    "graduationRate4anos": "60%",
    "medianSalary6anos": "$70,000",
    "tuition": "$77,892",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$30,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "14,120",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Enfermagem, Administração de Empresas, Ciência da Computação",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Early Action, Regular Decision",
    "contato": "enroll@drexel.edu"
  },
  {
    "id": 79,
    "nome": "University of Cincinnati",
    "sigla": "UC",
    "estado": "OH",
    "cidade": "Cincinnati",
    "setting": "urbano",
    "rankingNacional": "137",
    "taxaAceitacao": "83%",
    "faixaSAT": "1140-1340",
    "faixaACT": "24-30",
    "graduationRate4anos": "60%",
    "medianSalary6anos": "$55,000",
    "tuition": "$39,544",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "30,887",
    "percentualInternacionais": "5%",
    "majorsPrincipais": "Finanças, Administração de Empresas, Psicologia",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admissions@uc.edu"
  },
  {
    "id": 80,
    "nome": "University of Houston",
    "sigla": "UH",
    "estado": "TX",
    "cidade": "Houston",
    "setting": "urbano",
    "rankingNacional": "137",
    "taxaAceitacao": "66%",
    "faixaSAT": "1130-1330",
    "faixaACT": "23-29",
    "graduationRate4anos": "50%",
    "medianSalary6anos": "$55,000",
    "tuition": "$22,254",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "37,037",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Finanças, Psicologia, Contabilidade",
    "applicationFee": "$90",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@uh.edu"
  },
  {
    "id": 81,
    "nome": "University at Buffalo, SUNY",
    "sigla": "UB",
    "estado": "NY",
    "cidade": "Buffalo",
    "setting": "urbano",
    "rankingNacional": "76",
    "taxaAceitacao": "68%",
    "faixaSAT": "1180-1360",
    "faixaACT": "25-30",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$60,000",
    "tuition": "$30,010",
    "roomBoard": "$12,500",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "22,399",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Administração de Empresas, Psicologia, Biologia",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "ub-admissions@buffalo.edu"
  },
  {
    "id": 82,
    "nome": "Union College",
    "sigla": "Union",
    "estado": "NY",
    "cidade": "Schenectady",
    "setting": "suburbano",
    "rankingNacional": "39",
    "taxaAceitacao": "47%",
    "faixaSAT": "1300-1430",
    "faixaACT": "29-32",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$65,000",
    "tuition": "$85,600",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,296",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Engenharia Mecânica, Economia, Ciência Política",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@union.edu"
  },
  {
    "id": 83,
    "nome": "Stony Brook University",
    "sigla": "SBU",
    "estado": "NY",
    "cidade": "Stony Brook",
    "setting": "suburbano",
    "rankingNacional": "58",
    "taxaAceitacao": "48%",
    "faixaSAT": "1310-1500",
    "faixaACT": "28-34",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$68,000",
    "tuition": "$30,342",
    "roomBoard": "$14,000",
    "averageCostAfterAid": "$22,000",
    "averageNeedBasedAidPackage": "$18,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "17,502",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Biologia, Psicologia, Administração de Empresas",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "ugadmissions@stonybrook.edu"
  },
  {
    "id": 84,
    "nome": "Syracuse University",
    "sigla": "Syracuse",
    "estado": "NY",
    "cidade": "Syracuse",
    "setting": "urbano",
    "rankingNacional": "60",
    "taxaAceitacao": "52%",
    "faixaSAT": "1270-1440",
    "faixaACT": "28-32",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$68,000",
    "tuition": "$81,650",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$35,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "15,688",
    "percentualInternacionais": "9%",
    "majorsPrincipais": "Comunicação, Finanças, Administração de Empresas",
    "applicationFee": "$85",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "orange@syr.edu"
  },
  {
    "id": 85,
    "nome": "University of Illinois Chicago",
    "sigla": "UIC",
    "estado": "IL",
    "cidade": "Chicago",
    "setting": "urbano",
    "rankingNacional": "82",
    "taxaAceitacao": "78%",
    "faixaSAT": "1090-1360",
    "faixaACT": "22-29",
    "graduationRate4anos": "55%",
    "medianSalary6anos": "$60,000",
    "tuition": "$34,786",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "21,696",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Biologia, Psicologia, Enfermagem",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@uic.edu"
  },
  {
    "id": 86,
    "nome": "Denison University",
    "sigla": "Denison",
    "estado": "OH",
    "cidade": "Granville",
    "setting": "suburbano",
    "rankingNacional": "39",
    "taxaAceitacao": "27%",
    "faixaSAT": "1320-1460",
    "faixaACT": "30-33",
    "graduationRate4anos": "88%",
    "medianSalary6anos": "$65,000",
    "tuition": "$83,696",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$42,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,500",
    "percentualInternacionais": "11%",
    "majorsPrincipais": "Economia, Ciência Política, Psicologia",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Regular Decision",
    "contato": "admissions@denison.edu"
  },
  {
    "id": 87,
    "nome": "Embry-Riddle Aeronautical University - Worldwide",
    "sigla": "ERAU",
    "estado": "FL",
    "cidade": "Daytona Beach",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "70%",
    "faixaSAT": "N/A",
    "faixaACT": "N/A",
    "graduationRate4anos": "N/A",
    "medianSalary6anos": "$70,000",
    "tuition": "$13,120",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "7,551",
    "percentualInternacionais": "15%",
    "majorsPrincipais": "Aeronáutica, Administração de Empresas, Gestão de Operações",
    "applicationFee": "$50",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Rolling Admission",
    "contato": "worldwide@erau.edu"
  },
  {
    "id": 88,
    "nome": "University of Colorado Denver",
    "sigla": "CU Denver",
    "estado": "CO",
    "cidade": "Denver",
    "setting": "urbano",
    "rankingNacional": "163",
    "taxaAceitacao": "79%",
    "faixaSAT": "1050-1280",
    "faixaACT": "21-28",
    "graduationRate4anos": "50%",
    "medianSalary6anos": "$55,000",
    "tuition": "$36,064",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "14,120",
    "percentualInternacionais": "6%",
    "majorsPrincipais": "Biologia, Psicologia, Enfermagem",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@ucdenver.edu"
  },
  {
    "id": 89,
    "nome": "Moody Bible Institute",
    "sigla": "Moody",
    "estado": "IL",
    "cidade": "Chicago",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "94%",
    "faixaSAT": "1030-1290",
    "faixaACT": "21-27",
    "graduationRate4anos": "65%",
    "medianSalary6anos": "$45,000",
    "tuition": "$16,920",
    "roomBoard": "$10,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,222",
    "percentualInternacionais": "5%",
    "majorsPrincipais": "Teologia, Liderança Cristã, Música",
    "applicationFee": "$30",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Rolling Admission",
    "contato": "admissions@moody.edu"
  },
  {
    "id": 90,
    "nome": "Rhode Island School of Design",
    "sigla": "RISD",
    "estado": "RI",
    "cidade": "Providence",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "17%",
    "faixaSAT": "1210-1450",
    "faixaACT": "26-32",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$60,000",
    "tuition": "$85,600",
    "roomBoard": "$17,000",
    "averageCostAfterAid": "$45,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "2,148",
    "percentualInternacionais": "25%",
    "majorsPrincipais": "Design Gráfico, Pintura, Fotografia",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@risd.edu"
  },
  {
    "id": 91,
    "nome": "Dickinson College",
    "sigla": "Dickinson",
    "estado": "PA",
    "cidade": "Carlisle",
    "setting": "suburbano",
    "rankingNacional": "42",
    "taxaAceitacao": "37%",
    "faixaSAT": "1310-1460",
    "faixaACT": "29-33",
    "graduationRate4anos": "85%",
    "medianSalary6anos": "$60,000",
    "tuition": "$83,696",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$40,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,148",
    "percentualInternacionais": "8%",
    "majorsPrincipais": "Ciências do Meio Ambiente, Economia, Ciência Política",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App, Coalition",
    "tiposAplicacao": "Early Decision, Early Action, Regular Decision",
    "contato": "admit@dickinson.edu"
  },
  {
    "id": 92,
    "nome": "Florida Institute of Technology",
    "sigla": "Florida Tech",
    "estado": "FL",
    "cidade": "Melbourne",
    "setting": "suburbano",
    "rankingNacional": "151",
    "taxaAceitacao": "64%",
    "faixaSAT": "1140-1340",
    "faixaACT": "24-29",
    "graduationRate4anos": "55%",
    "medianSalary6anos": "$65,000",
    "tuition": "$58,120",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$30,000",
    "averageNeedBasedAidPackage": "$25,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "3,490",
    "percentualInternacionais": "18%",
    "majorsPrincipais": "Engenharia Aeroespacial, Biologia, Engenharia Mecânica",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Action, Regular Decision",
    "contato": "admission@fit.edu"
  },
  {
    "id": 93,
    "nome": "Santa Monica College",
    "sigla": "SMC",
    "estado": "CA",
    "cidade": "Santa Monica",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "100%",
    "faixaSAT": "N/A",
    "faixaACT": "N/A",
    "graduationRate4anos": "N/A",
    "medianSalary6anos": "$45,000",
    "tuition": "$9,923",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$8,000",
    "averageNeedBasedAidPackage": "$5,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "25,845",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Administração de Empresas, Liberal Arts, Estudos de Cinema",
    "applicationFee": "N/A",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Rolling Admission",
    "contato": "admissions@smc.edu"
  },
  {
    "id": 94,
    "nome": "Andrews University",
    "sigla": "Andrews",
    "estado": "MI",
    "cidade": "Berrien Springs",
    "setting": "suburbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "70%",
    "faixaSAT": "1040-1280",
    "faixaACT": "21-27",
    "graduationRate4anos": "45%",
    "medianSalary6anos": "$50,000",
    "tuition": "$46,396",
    "roomBoard": "$10,000",
    "averageCostAfterAid": "$20,000",
    "averageNeedBasedAidPackage": "$15,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "1,579",
    "percentualInternacionais": "12%",
    "majorsPrincipais": "Enfermagem, Administração de Empresas, Biologia",
    "applicationFee": "$30",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Rolling Admission",
    "contato": "adventist@andrews.edu"
  },
  {
    "id": 95,
    "nome": "Clark University",
    "sigla": "Clark",
    "estado": "MA",
    "cidade": "Worcester",
    "setting": "urbano",
    "rankingNacional": "105",
    "taxaAceitacao": "48%",
    "faixaSAT": "1270-1420",
    "faixaACT": "27-32",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$60,000",
    "tuition": "$71,748",
    "roomBoard": "$16,000",
    "averageCostAfterAid": "$40,000",
    "averageNeedBasedAidPackage": "$30,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "2,222",
    "percentualInternacionais": "10%",
    "majorsPrincipais": "Psicologia, Biologia, Estudos de Cinema",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision I & II, Early Action, Regular Decision",
    "contato": "admissions@clarku.edu"
  },
  {
    "id": 96,
    "nome": "Central Washington University",
    "sigla": "CWU",
    "estado": "WA",
    "cidade": "Ellensburg",
    "setting": "rural",
    "rankingNacional": "N/A",
    "taxaAceitacao": "94%",
    "faixaSAT": "990-1180",
    "faixaACT": "18-24",
    "graduationRate4anos": "40%",
    "medianSalary6anos": "$50,000",
    "tuition": "$28,096",
    "roomBoard": "$11,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "9,070",
    "percentualInternacionais": "3%",
    "majorsPrincipais": "Educação Física, Administração de Empresas, Administração Pública",
    "applicationFee": "$50",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Rolling Admission",
    "contato": "admissions@cwu.edu"
  },
  {
    "id": 97,
    "nome": "California State University, San Bernardino",
    "sigla": "CSUSB",
    "estado": "CA",
    "cidade": "San Bernardino",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "91%",
    "faixaSAT": "940-1130",
    "faixaACT": "17-23",
    "graduationRate4anos": "35%",
    "medianSalary6anos": "$50,000",
    "tuition": "$22,454",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$12,000",
    "averageNeedBasedAidPackage": "$8,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "16,518",
    "percentualInternacionais": "4%",
    "majorsPrincipais": "Administração de Empresas, Psicologia, Justiça Criminal",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "admissions@csusb.edu"
  },
  {
    "id": 98,
    "nome": "California State University - Long Beach",
    "sigla": "CSULB",
    "estado": "CA",
    "cidade": "Long Beach",
    "setting": "urbano",
    "rankingNacional": "N/A",
    "taxaAceitacao": "47%",
    "faixaSAT": "1080-1290",
    "faixaACT": "21-27",
    "graduationRate4anos": "50%",
    "medianSalary6anos": "$55,000",
    "tuition": "$22,454",
    "roomBoard": "$12,000",
    "averageCostAfterAid": "$15,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "30,686",
    "percentualInternacionais": "5%",
    "majorsPrincipais": "Administração de Empresas, Psicologia, Comunicação",
    "applicationFee": "$70",
    "plataformaInscricao": "site próprio",
    "tiposAplicacao": "Regular Decision",
    "contato": "outreach@csulb.edu"
  },
  {
    "id": 99,
    "nome": "University of Idaho",
    "sigla": "U of I",
    "estado": "ID",
    "cidade": "Moscow",
    "setting": "suburbano",
    "rankingNacional": "194",
    "taxaAceitacao": "79%",
    "faixaSAT": "1070-1280",
    "faixaACT": "21-28",
    "graduationRate4anos": "45%",
    "medianSalary6anos": "$50,000",
    "tuition": "$29,742",
    "roomBoard": "$11,000",
    "averageCostAfterAid": "$18,000",
    "averageNeedBasedAidPackage": "$10,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS",
    "totalAlunos": "9,684",
    "percentualInternacionais": "4%",
    "majorsPrincipais": "Administração de Empresas, Ciências Biológicas, Psicologia",
    "applicationFee": "$60",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Rolling Admission",
    "contato": "admit@uidaho.edu"
  },
  {
    "id": 100,
    "nome": "University of Florida",
    "sigla": "UF",
    "estado": "FL",
    "cidade": "Gainesville",
    "setting": "urbano",
    "rankingNacional": "29",
    "taxaAceitacao": "23%",
    "faixaSAT": "1350-1500",
    "faixaACT": "30-34",
    "graduationRate4anos": "78%",
    "medianSalary6anos": "$68,000",
    "tuition": "$45,656",
    "roomBoard": "$13,000",
    "averageCostAfterAid": "$25,000",
    "averageNeedBasedAidPackage": "$20,000",
    "politicaFinanceira": "need-based",
    "tiposBolsa": "necessidade, mérito",
    "testesProficiencia": "TOEFL, IELTS, Duolingo English Test",
    "totalAlunos": "35,807",
    "percentualInternacionais": "7%",
    "majorsPrincipais": "Biologia, Finanças, Psicologia",
    "applicationFee": "$30",
    "plataformaInscricao": "Common App",
    "tiposAplicacao": "Early Decision, Regular Decision",
    "contato": "admissions@ufl.edu"
  }
]