export const oportunidades = [
  {
    "id": 1,
    "nome": "Programa de Verão em Inovação Tecnológica",
    "imagem": "https://wallpapers.com/images/high/travel-pictures-2w3ecn151g4ney5s.webp",
    "pais": "Estados Unidos",
    "cidade": "Boston",
    "instituicaoResponsavel": "MIT - Massachusetts Institute of Technology",
    "tipo": "Curso de verão",
    "descricao": "Imersão de três semanas em inovação, robótica e inteligência artificial, com aulas e projetos práticos liderados por pesquisadores do MIT.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18–24",
    "requisitosIdioma": "Inglês (TOEFL iBT 100+)",
    "requisitosEspecificos": "Histórico acadêmico de excelência em áreas de STEM.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Passagem, hospedagem, alimentação, taxa de matrícula e seguro.",
    "custosExtras": "Despesas pessoais e de transporte local.",
    "duracao": "3 semanas",
    "prazoInscricao": "15/03/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Formulário online na plataforma oficial do programa.",
    "linkOficial": "https://www.mit.edu/summer-tech-innovation",
    "contato": "summer-tech-program@mit.edu"
  },
  {
    "id": 2,
    "nome": "Bolsa de Doutorado em Energias Renováveis",
    "imagem": "https://images.unsplash.com/photo-1755398105315-a124a12152da?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Alemanha",
    "cidade": "Berlim",
    "instituicaoResponsavel": "Universidade Técnica de Berlim",
    "tipo": "Doutorado",
    "descricao": "Pesquisa de 4 anos com foco em novas tecnologias de energia eólica e solar, com bolsa de pesquisa integral e colaboração com a indústria.",
    "nivelEnsino": "Doutorado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Alemão (B2+) ou Inglês (C1+)",
    "requisitosEspecificos": "Mestrado completo em engenharia ou física, proposta de pesquisa original e relevante.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula, salário mensal para pesquisa, seguro-saúde e passagens aéreas anuais.",
    "custosExtras": "Despesas pessoais.",
    "duracao": "4 anos",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de currículo e proposta, entrevista com o orientador.",
    "processoInscricao": "Envio de documentos por e-mail para o departamento acadêmico.",
    "linkOficial": "https://www.tu-berlin.de/en/phd-renewables",
    "contato": "phd-admissions@tu-berlin.de"
  },
  {
    "id": 3,
    "nome": "Intercâmbio Cultural na Costa Rica",
    "imagem": "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
    "pais": "Costa Rica",
    "cidade": "San José",
    "instituicaoResponsavel": "Organização Pura Vida Voluntariado",
    "tipo": "Trabalho voluntário",
    "descricao": "Programa de trabalho voluntário focado em conservação ambiental e educação em comunidades rurais. Inclui aulas de espanhol e atividades de imersão cultural.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16–25",
    "requisitosIdioma": "Espanhol (B1)",
    "requisitosEspecificos": "Paixão por sustentabilidade e interesse em trabalho comunitário.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa do programa que cobre hospedagem, alimentação e atividades. Passagem aérea e seguro-viagem.",
    "duracao": "4 semanas",
    "prazoInscricao": "01/05/2026",
    "etapasSelecao": "Análise do formulário e chamada de vídeo com a equipe do programa.",
    "processoInscricao": "Preenchimento de formulário no site oficial.",
    "linkOficial": "https://www.puravidavoluntariado.org",
    "contato": "info@puravidavoluntariado.org"
  },
  {
    "id": 4,
    "nome": "Bolsa de Pesquisa para Pós-Doutorado em Antropologia",
    "imagem": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05",
    "pais": "França",
    "cidade": "Paris",
    "instituicaoResponsavel": "EHESS - École des Hautes Études en Sciences Sociales",
    "tipo": "Pesquisa",
    "descricao": "Oportunidade de 1 ano para pesquisadores em início de carreira aprofundarem seus estudos sobre migração contemporânea na Europa.",
    "nivelEnsino": "Pós-Doutorado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Francês (C1) ou Inglês (C1)",
    "requisitosEspecificos": "Doutorado concluído nos últimos 5 anos, projeto de pesquisa original e relevante.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Bolsa de pesquisa mensal, seguro-saúde e acesso a bibliotecas e centros de pesquisa.",
    "custosExtras": "Passagem aérea e despesas pessoais.",
    "duracao": "1 ano",
    "prazoInscricao": "10/06/2026",
    "etapasSelecao": "Análise da proposta de pesquisa e entrevista com o comitê de seleção.",
    "processoInscricao": "Envio de documentos por e-mail para o comitê.",
    "linkOficial": "https://www.ehess.fr/post-doc-anthro",
    "contato": "postdoc.selection@ehess.fr"
  },
  {
    "id": 5,
    "nome": "Programa de Graduação em Design de Jogos",
    "imagem": "https://images.pexels.com/photos/2387418/pexels-photo-2387418.jpeg",
    "pais": "Canadá",
    "cidade": "Vancouver",
    "instituicaoResponsavel": "Vancouver Film School",
    "tipo": "Graduação",
    "descricao": "Curso intensivo de um ano para se tornar um designer de jogos. Foco em narrativa, mecânica de jogo e prototipagem. Portfólio de projetos reais ao final.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 6.5+)",
    "requisitosEspecificos": "Portfólio de trabalhos criativos (desenhos, histórias, projetos de programação).",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem aérea, hospedagem, alimentação e seguro.",
    "duracao": "1 ano",
    "prazoInscricao": "01/07/2026",
    "etapasSelecao": "Análise do portfólio e entrevista via Skype.",
    "processoInscricao": "Inscrição via site da escola, com envio de documentos.",
    "linkOficial": "https://www.vfs.edu/programs/game-design",
    "contato": "admissions@vfs.edu"
  },
  {
    "id": 6,
    "nome": "Estágio em Relações Internacionais",
    "imagem": "https://images.unsplash.com/photo-1454496522488-7a8e488e8606",
    "pais": "Suíça",
    "cidade": "Genebra",
    "instituicaoResponsavel": "Organização das Nações Unidas (ONU)",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses na sede da ONU em Genebra. Foco em política internacional, direitos humanos e diplomacia.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês e/ou Francês (fluência)",
    "requisitosEspecificos": "Ser estudante de graduação ou mestrado, ter concluído pelo menos 2 anos de estudo.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Todas as despesas são de responsabilidade do estudante (hospedagem, alimentação, passagem, visto).",
    "duracao": "6 meses",
    "prazoInscricao": "15/11/2025",
    "etapasSelecao": "Análise de currículo, teste de proficiência e entrevista.",
    "processoInscricao": "Plataforma oficial de carreiras da ONU.",
    "linkOficial": "https://careers.un.org/lbw/jobdetail.aspx?id=12345",
    "contato": "internships@un.org"
  },
  {
    "id": 7,
    "nome": "Curso de Idiomas em Tóquio",
    "imagem": "https://images.pexels.com/photos/1032650/pexels-photo-1032650.jpeg",
    "pais": "Japão",
    "cidade": "Tóquio",
    "instituicaoResponsavel": "Escola de Línguas de Shinjuku",
    "tipo": "Curso de idiomas",
    "descricao": "Curso intensivo de japonês para todos os níveis, com foco em comunicação e cultura. Inclui atividades culturais e excursões pela cidade.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Não há (curso para iniciantes e avançados)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa de matrícula, passagem, hospedagem, alimentação e seguro.",
    "duracao": "8 semanas",
    "prazoInscricao": "15/05/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.shinjuku-language-school.jp/summer-course",
    "contato": "contact@shinjuku-language-school.jp"
  },
  {
    "id": 8,
    "nome": "Bolsa de Mestrado em Sustentabilidade Ambiental",
    "imagem": "https://images.unsplash.com/photo-1448375240586-882707db888b",
    "pais": "Suécia",
    "cidade": "Estocolmo",
    "instituicaoResponsavel": "KTH Royal Institute of Technology",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em soluções sustentáveis para desafios ambientais urbanos. Combina teoria e projetos práticos.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Graduação em engenharia, ciências ambientais ou áreas relacionadas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da KTH.",
    "linkOficial": "https://www.kth.se/en/master/sustainable-development",
    "contato": "master-admissions@kth.se"
  },
  {
    "id": 9,
    "nome": "Bolsa de Ensino Médio nos Países Baixos",
    "imagem": "https://images.pexels.com/photos/38136/pexels-photo-38136.jpeg",
    "pais": "Países Baixos",
    "cidade": "Amsterdã",
    "instituicaoResponsavel": "AFS Intercultural Programs",
    "tipo": "High School",
    "descricao": "Um ano de intercâmbio escolar no ensino médio holandês. Oportunidade de morar com uma família local e estudar em uma escola pública.",
    "nivelEnsino": "Ensino Médio",
    "faixaEtaria": "15–17",
    "requisitosIdioma": "Inglês (B1+)",
    "requisitosEspecificos": "Ser estudante de escola pública e ter notas acima da média.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Passagem, hospedagem, alimentação, seguro e taxa de matrícula da escola.",
    "custosExtras": "Despesas pessoais.",
    "duracao": "10 meses",
    "prazoInscricao": "01/09/2025",
    "etapasSelecao": "Prova escrita, entrevista com o comitê, análise de documentos.",
    "processoInscricao": "Inscrição online no site da AFS.",
    "linkOficial": "https://www.afs.org.br/highschool-netherlands",
    "contato": "info@afs.org.br"
  },
  {
    "id": 10,
    "nome": "Mobilidade Acadêmica na Universidade de Coimbra",
    "imagem": "https://images.unsplash.com/photo-1426604966848-d7adac402bff",
    "pais": "Portugal",
    "cidade": "Coimbra",
    "instituicaoResponsavel": "Universidade de Coimbra",
    "tipo": "Mobilidade acadêmica",
    "descricao": "Semestre de intercâmbio para estudantes de graduação de países da CPLP. Oportunidade de cursar matérias e viver a vida universitária em Portugal.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Português (fluência)",
    "requisitosEspecificos": "Estar matriculado em uma universidade parceira no Brasil, Angola ou Moçambique.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Taxa de matrícula na universidade.",
    "custosExtras": "Passagem, moradia, alimentação e seguro.",
    "duracao": "1 semestre",
    "prazoInscricao": "30/10/2025",
    "etapasSelecao": "Análise documental e aprovação da universidade de origem.",
    "processoInscricao": "Inscrição via escritório internacional da sua universidade.",
    "linkOficial": "https://www.uc.pt/en/internacional/mobility",
    "contato": "dri@uc.pt"
  },
  {
    "id": 11,
    "nome": "Curso Intensivo de Verão em Economia",
    "imagem": "https://images.unsplash.com/photo-1621595186259-c290a1ed2e84?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Reino Unido",
    "cidade": "Londres",
    "instituicaoResponsavel": "London School of Economics (LSE)",
    "tipo": "Curso de verão",
    "descricao": "Duas semanas de aulas intensivas sobre microeconomia e macroeconomia avançadas, ministradas por professores da LSE. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 7.0+)",
    "requisitosEspecificos": "Estar cursando graduação em economia, finanças ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa.",
    "custosExtras": "Passagem aérea, hospedagem, alimentação e seguro.",
    "duracao": "2 semanas",
    "prazoInscricao": "01/04/2026",
    "etapasSelecao": "Análise de currículo e notas.",
    "processoInscricao": "Inscrição na plataforma online da LSE.",
    "linkOficial": "https://www.lse.ac.uk/summer-school/economics",
    "contato": "summerschool@lse.ac.uk"
  },
  {
    "id": 12,
    "nome": "MBA em Gestão de Negócios na Ásia",
    "imagem": "https://images.unsplash.com/photo-1601004128509-f192b4517319?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Singapura",
    "cidade": "Singapura",
    "instituicaoResponsavel": "National University of Singapore (NUS)",
    "tipo": "MBA",
    "descricao": "MBA de 18 meses com foco em liderança global e inovação no contexto asiático. Parcerias com empresas de tecnologia e startups.",
    "nivelEnsino": "MBA",
    "faixaEtaria": "25+",
    "requisitosIdioma": "Inglês (GMAT 650+ e TOEFL iBT 100+)",
    "requisitosEspecificos": "Experiência profissional mínima de 3 anos, liderança comprovada e potencial de crescimento.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 70% da taxa de matrícula.",
    "custosExtras": "Taxa de matrícula (parcial), passagem aérea, hospedagem, alimentação e seguro.",
    "duracao": "18 meses",
    "prazoInscricao": "01/12/2025",
    "etapasSelecao": "Análise de documentos, redação, GMAT e entrevista.",
    "processoInscricao": "Inscrição online no site da NUS.",
    "linkOficial": "https://mba.nus.edu.sg/",
    "contato": "mba_admissions@nus.edu.sg"
  },
  {
    "id": 13,
    "nome": "Curso de Idiomas em Sevilha",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Espanha",
    "cidade": "Sevilha",
    "instituicaoResponsavel": "Instituto Cervantes",
    "tipo": "Curso de idiomas",
    "descricao": "Curso de espanhol para todos os níveis, com foco na cultura e tradições andaluzas. Inclui atividades de imersão cultural e passeios pela cidade.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Nenhum (curso para iniciantes e avançados)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa de matrícula, passagem, hospedagem, alimentação e seguro.",
    "duracao": "4 semanas",
    "prazoInscricao": "15/06/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Inscrição online no site do Instituto Cervantes.",
    "linkOficial": "https://www.cervantes.es/seville/language-courses",
    "contato": "sevilla@cervantes.es"
  },
  {
    "id": 14,
    "nome": "High School na Alemanha",
    "imagem": "https://images.unsplash.com/photo-1510619586150-1376d29944a1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Alemanha",
    "cidade": "Berlim",
    "instituicaoResponsavel": "AFS Intercultural Programs",
    "tipo": "High School",
    "descricao": "Um ano de intercâmbio escolar no ensino médio alemão. Oportunidade de morar com uma família local e estudar em uma escola pública.",
    "nivelEnsino": "Ensino Médio",
    "faixaEtaria": "15–17",
    "requisitosIdioma": "Alemão (A2+)",
    "requisitosEspecificos": "Ser estudante de escola pública e ter notas acima da média.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Passagem, hospedagem, alimentação, seguro e taxa de matrícula da escola.",
    "custosExtras": "Despesas pessoais.",
    "duracao": "10 meses",
    "prazoInscricao": "01/09/2025",
    "etapasSelecao": "Prova escrita, entrevista com o comitê, análise de documentos.",
    "processoInscricao": "Inscrição online no site da AFS.",
    "linkOficial": "https://www.afs.org.br/highschool-germany",
    "contato": "info@afs.org.br"
  },
  {
    "id": 15,
    "nome": "Curso de Verão em Fotografia na Itália",
    "imagem": "https://images.unsplash.com/photo-1512496011470-76133be929d2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Itália",
    "cidade": "Florença",
    "instituicaoResponsavel": "Academia de Belas Artes de Florença",
    "tipo": "Curso de verão",
    "descricao": "Duas semanas de imersão em fotografia, com aulas teóricas e saídas práticas pela cidade. Foco em fotografia de rua e paisagem.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Italiano (B1) ou Inglês (B2)",
    "requisitosEspecificos": "Portfólio de 5 a 10 fotos.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "2 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da academia.",
    "linkOficial": "https://www.accademiafirenze.it/summer-photography",
    "contato": "info@accademiafirenze.it"
  },
  {
    "id": 16,
    "nome": "Estágio em Engenharia Civil na Austrália",
    "imagem": "https://images.unsplash.com/photo-1560965319-e58721c0b396?q=80&w=1980&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Austrália",
    "cidade": "Sydney",
    "instituicaoResponsavel": "Empresa de Construção Global",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de engenharia civil, com foco em gestão de projetos e sustentabilidade na construção.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 6.5+)",
    "requisitosEspecificos": "Estar cursando a partir do 5º semestre de engenharia civil.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a empresa.",
    "linkOficial": "https://www.global-construction.com.au/internship",
    "contato": "internships@global-construction.com.au"
  },
  {
    "id": 17,
    "nome": "Mestrado em Gestão Pública em Oxford",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Reino Unido",
    "cidade": "Oxford",
    "instituicaoResponsavel": "Universidade de Oxford",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 1 ano focado em políticas públicas, liderança e governança global. Prepara futuros líderes para o setor público e não-governamental.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 110+)",
    "requisitosEspecificos": "Graduação em ciências sociais ou áreas correlatas, experiência profissional em gestão pública ou terceiro setor.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "1 ano",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental, ensaio, GMAT/GRE e entrevista.",
    "processoInscricao": "Inscrição na plataforma online da universidade.",
    "linkOficial": "https://www.ox.ac.uk/admissions/graduate/courses/master-public-policy",
    "contato": "admissions@bsg.ox.ac.uk"
  },
  {
    "id": 18,
    "nome": "Curso de Idiomas em Barcelona",
    "imagem": "https://images.unsplash.com/photo-1542831371-29b0f74f945c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Espanha",
    "cidade": "Barcelona",
    "instituicaoResponsavel": "Escola de Idiomas Bcn",
    "tipo": "Curso de idiomas",
    "descricao": "Curso intensivo de espanhol para todos os níveis, com foco em conversação e cultura catalã. Inclui atividades culturais e passeios pela cidade.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Nenhum (curso para iniciantes e avançados)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa de matrícula, passagem, hospedagem, alimentação e seguro.",
    "duracao": "4 semanas",
    "prazoInscricao": "15/06/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.bcnschooloflanguages.com/spanish-courses",
    "contato": "info@bcnschooloflanguages.com"
  },
  {
    "id": 19,
    "nome": "Curso de Verão em Música em Viena",
    "imagem": "https://images.unsplash.com/photo-1594950346077-d7e7c84495de?q=80&w=1925&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Áustria",
    "cidade": "Viena",
    "instituicaoResponsavel": "Universidade de Música e Artes de Viena",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em música clássica, com aulas de instrumento, teoria musical e história da música. Ideal para estudantes de música.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Alemão (B1) ou Inglês (B2)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças musicais.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da universidade.",
    "linkOficial": "https://www.mdw.ac.at/summer-music-program",
    "contato": "summer-music@mdw.ac.at"
  },
  {
    "id": 20,
    "nome": "Estágio em Arquitetura em Copenhague",
    "imagem": "https://images.unsplash.com/photo-1542831371-29b0f74f945c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Dinamarca",
    "cidade": "Copenhague",
    "instituicaoResponsavel": "Escritório de Arquitetura",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de arquitetura, com foco em projetos sustentáveis e design urbano. Oportunidade de trabalhar em um escritório de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1)",
    "requisitosEspecificos": "Estar cursando arquitetura ou design urbano, portfólio de projetos.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e portfólio, entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para o escritório.",
    "linkOficial": "https://www.architecture-office.dk/internship",
    "contato": "internships@architecture-office.dk"
  },
  {
    "id": 21,
    "nome": "Programa de Verão em Artes em Nova York",
    "imagem": "https://images.unsplash.com/photo-1540841267425-4700d8d06b3e?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Estados Unidos",
    "cidade": "Nova York",
    "instituicaoResponsavel": "Parsons School of Design",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em design de moda, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de arte.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da Parsons.",
    "linkOficial": "https://www.newschool.edu/parsons/summer-programs",
    "contato": "summer-programs@newschool.edu"
  },
  {
    "id": 22,
    "nome": "Trabalho Voluntário em Conservação Marinha",
    "imagem": "https://images.unsplash.com/photo-1517441865463-b6d3c2602188?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Tailândia",
    "cidade": "Koh Tao",
    "instituicaoResponsavel": "Organização de Conservação Marinha",
    "tipo": "Trabalho voluntário",
    "descricao": "Programa de trabalho voluntário focado em conservação marinha e educação em comunidades costeiras. Inclui aulas de mergulho e atividades de imersão cultural.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (B1+)",
    "requisitosEspecificos": "Paixão por conservação marinha e interesse em trabalho comunitário.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa do programa que cobre hospedagem, alimentação e atividades. Passagem aérea e seguro-viagem.",
    "duracao": "4 semanas",
    "prazoInscricao": "01/05/2026",
    "etapasSelecao": "Análise do formulário e chamada de vídeo com a equipe do programa.",
    "processoInscricao": "Preenchimento de formulário no site oficial.",
    "linkOficial": "https://www.marineconservation.org/volunteer-thailand",
    "contato": "info@marineconservation.org"
  },
  {
    "id": 23,
    "nome": "Bolsa de Doutorado em Biologia Marinha",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Noruega",
    "cidade": "Tromsø",
    "instituicaoResponsavel": "Universidade Ártica da Noruega",
    "tipo": "Doutorado",
    "descricao": "Pesquisa de 4 anos com foco em ecossistemas marinhos polares, com bolsa de pesquisa integral e acesso a laboratórios de ponta.",
    "nivelEnsino": "Doutorado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (C1+)",
    "requisitosEspecificos": "Mestrado completo em biologia marinha ou áreas relacionadas, proposta de pesquisa original e relevante.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula, salário mensal para pesquisa, seguro-saúde e passagens aéreas anuais.",
    "custosExtras": "Despesas pessoais.",
    "duracao": "4 anos",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de currículo e proposta, entrevista com o orientador.",
    "processoInscricao": "Envio de documentos por e-mail para o departamento acadêmico.",
    "linkOficial": "https://uit.no/research/phd-marine-biology",
    "contato": "phd-admissions@uit.no"
  },
  {
    "id": 24,
    "nome": "Programa de Verão em Robótica na Alemanha",
    "imagem": "https://images.unsplash.com/photo-1510619586150-1376d29944a1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Alemanha",
    "cidade": "Munique",
    "instituicaoResponsavel": "Universidade Técnica de Munique (TUM)",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em robótica, com aulas teóricas e projetos práticos. Ideal para estudantes de engenharia e ciência da computação.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Histórico acadêmico de excelência em áreas de STEM.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa.",
    "custosExtras": "Passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise documental.",
    "processoInscricao": "Inscrição na plataforma online da TUM.",
    "linkOficial": "https://www.tum.de/en/studies/summer-school-robotics",
    "contato": "summer-school@tum.de"
  },
  {
    "id": 25,
    "nome": "Intercâmbio Cultural na Tailândia",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Tailândia",
    "cidade": "Chiang Mai",
    "instituicaoResponsavel": "Organização de Intercâmbio Cultural",
    "tipo": "Intercâmbio cultural",
    "descricao": "Programa de 4 semanas focado em cultura tailandesa e trabalho voluntário em comunidades rurais. Inclui aulas de culinária, visita a templos e trilhas pela floresta.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Inglês (B1+)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa do programa que cobre hospedagem, alimentação e atividades. Passagem aérea e seguro-viagem.",
    "duracao": "4 semanas",
    "prazoInscricao": "01/05/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Preenchimento de formulário no site oficial.",
    "linkOficial": "https://www.culturalexchange.org/thailand-program",
    "contato": "info@culturalexchange.org"
  },
  {
    "id": 26,
    "nome": "Curso de Idiomas em Berlim",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Alemanha",
    "cidade": "Berlim",
    "instituicaoResponsavel": "Escola de Línguas Berlitz",
    "tipo": "Curso de idiomas",
    "descricao": "Curso intensivo de alemão para todos os níveis, com foco em conversação e cultura alemã. Inclui atividades culturais e passeios pela cidade.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Nenhum (curso para iniciantes e avançados)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa de matrícula, passagem, hospedagem, alimentação e seguro.",
    "duracao": "4 semanas",
    "prazoInscricao": "15/06/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.berlitz.de/en/language-courses/german-berlin",
    "contato": "info@berlitz.de"
  },
  {
    "id": 27,
    "nome": "Bolsa de Graduação em Engenharia de Software",
    "imagem": "https://images.unsplash.com/photo-1542831371-29b0f74f945c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Canadá",
    "cidade": "Toronto",
    "instituicaoResponsavel": "Universidade de Toronto",
    "tipo": "Graduação",
    "descricao": "Bolsa integral para 4 anos de estudo em engenharia de software. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria de tecnologia.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (TOEFL iBT 100+)",
    "requisitosEspecificos": "Notas de excelência no ensino médio, histórico de liderança e projetos extracurriculares.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa, moradia e seguro-saúde.",
    "custosExtras": "Passagem aérea, alimentação e despesas pessoais.",
    "duracao": "4 anos",
    "prazoInscricao": "15/12/2025",
    "etapasSelecao": "Análise documental, redação, entrevista online e teste de habilidades.",
    "processoInscricao": "Inscrição online no site da universidade.",
    "linkOficial": "https://www.utoronto.ca/admission/international-students/scholarships/software-engineering",
    "contato": "admissions@utoronto.ca"
  },
  {
    "id": 28,
    "nome": "Curso de Verão em Cinema em Paris",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "França",
    "cidade": "Paris",
    "instituicaoResponsavel": "École de la Cité",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em cinema, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Francês (B2)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de arte.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.ecole-cite.fr/summer-cinema-program",
    "contato": "summer-programs@ecole-cite.fr"
  },
  {
    "id": 29,
    "nome": "Estágio em Relações Públicas em Xangai",
    "imagem": "https://images.unsplash.com/photo-1621595186259-c290a1ed2e84?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "China",
    "cidade": "Xangai",
    "instituicaoResponsavel": "Agência de Relações Públicas",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de relações públicas, com foco em comunicação e marketing digital. Oportunidade de trabalhar em uma agência de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1) e Mandarim (B1)",
    "requisitosEspecificos": "Estar cursando relações públicas ou marketing.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e portfólio, entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a agência.",
    "linkOficial": "https://www.pr-agency.cn/internship",
    "contato": "internships@pr-agency.cn"
  },
  {
    "id": 30,
    "nome": "Programa de Verão em Meio Ambiente na Suíça",
    "imagem": "https://images.unsplash.com/photo-1517441865463-b6d3c2602188?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Suíça",
    "cidade": "Genebra",
    "instituicaoResponsavel": "Universidade de Genebra",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em meio ambiente, com aulas teóricas e projetos práticos. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Histórico acadêmico de excelência em áreas de ciências ambientais.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa.",
    "custosExtras": "Passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise documental.",
    "processoInscricao": "Inscrição na plataforma online da universidade.",
    "linkOficial": "https://www.unige.ch/summer-school-environment",
    "contato": "summer-school@unige.ch"
  },
  {
    "id": 31,
    "nome": "Bolsa de Mestrado em Neurociência em Stanford",
    "imagem": "https://images.unsplash.com/photo-1621595186259-c290a1ed2e84?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Estados Unidos",
    "cidade": "Palo Alto",
    "instituicaoResponsavel": "Stanford University",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em pesquisa em neurociência computacional e biológica. Oportunidade de trabalhar em laboratórios de ponta e ter contato com pesquisadores renomados.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (GRE 320+ e TOEFL iBT 100+)",
    "requisitosEspecificos": "Graduação em neurociência, psicologia ou áreas relacionadas, experiência em pesquisa.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa, moradia, alimentação e seguro.",
    "custosExtras": "Passagem aérea e despesas pessoais.",
    "duracao": "2 anos",
    "prazoInscricao": "15/12/2025",
    "etapasSelecao": "Análise documental, redação, GRE e entrevista.",
    "processoInscricao": "Inscrição online no site da universidade.",
    "linkOficial": "https://neuroscience.stanford.edu/graduate-program",
    "contato": "neuroscience@stanford.edu"
  },
  {
    "id": 32,
    "nome": "High School na Nova Zelândia",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Nova Zelândia",
    "cidade": "Auckland",
    "instituicaoResponsavel": "AFS Intercultural Programs",
    "tipo": "High School",
    "descricao": "Um ano de intercâmbio escolar no ensino médio neozelandês. Oportunidade de morar com uma família local e estudar em uma escola pública.",
    "nivelEnsino": "Ensino Médio",
    "faixaEtaria": "15–17",
    "requisitosIdioma": "Inglês (B1+)",
    "requisitosEspecificos": "Ser estudante de escola pública e ter notas acima da média.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Passagem, hospedagem, alimentação, seguro e taxa de matrícula da escola.",
    "custosExtras": "Despesas pessoais.",
    "duracao": "10 meses",
    "prazoInscricao": "01/09/2025",
    "etapasSelecao": "Prova escrita, entrevista com o comitê, análise de documentos.",
    "processoInscricao": "Inscrição online no site da AFS.",
    "linkOficial": "https://www.afs.org.br/highschool-newzealand",
    "contato": "info@afs.org.br"
  },
  {
    "id": 33,
    "nome": "Curso de Idiomas em Roma",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Itália",
    "cidade": "Roma",
    "instituicaoResponsavel": "Escola de Idiomas Leonardo da Vinci",
    "tipo": "Curso de idiomas",
    "descricao": "Curso intensivo de italiano para todos os níveis, com foco em conversação e cultura italiana. Inclui atividades culturais e passeios pela cidade.",
    "nivelEnsino": "Ensino Médio, Graduação",
    "faixaEtaria": "16+",
    "requisitosIdioma": "Nenhum (curso para iniciantes e avançados)",
    "requisitosEspecificos": "Nenhum.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Sem bolsa",
    "coberturaBolsa": "Não aplicável.",
    "custosExtras": "Taxa de matrícula, passagem, hospedagem, alimentação e seguro.",
    "duracao": "4 semanas",
    "prazoInscricao": "15/06/2026",
    "etapasSelecao": "Nenhum, apenas inscrição.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.scuolaleonardo.com/roma-italian-courses",
    "contato": "info@scuolaleonardo.com"
  },
  {
    "id": 34,
    "nome": "Bolsa de Mestrado em Ciência de Dados",
    "imagem": "https://images.unsplash.com/photo-1621595186259-c290a1ed2e84?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Japão",
    "cidade": "Tóquio",
    "instituicaoResponsavel": "Universidade de Tóquio",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em ciência de dados e inteligência artificial. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria de tecnologia.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 100+) ou Japonês (JLPT N2+)",
    "requisitosEspecificos": "Graduação em engenharia, ciência da computação ou áreas relacionadas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da universidade.",
    "linkOficial": "https://www.u-tokyo.ac.jp/en/admissions/graduate/data-science",
    "contato": "master-admissions@u-tokyo.ac.jp"
  },
  {
    "id": 35,
    "nome": "Curso de Verão em Ciência Política na China",
    "imagem": "https://images.unsplash.com/photo-1621595186259-c290a1ed2e84?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "China",
    "cidade": "Pequim",
    "instituicaoResponsavel": "Universidade de Pequim",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em ciência política, com aulas teóricas e projetos práticos. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Histórico acadêmico de excelência em áreas de ciências sociais.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa.",
    "custosExtras": "Passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise documental.",
    "processoInscricao": "Inscrição na plataforma online da universidade.",
    "linkOficial": "https://www.pku.edu.cn/en/summer-school-political-science",
    "contato": "summer-school@pku.edu.cn"
  },
  {
    "id": 36,
    "nome": "Bolsa de Mestrado em Direito Internacional",
    "imagem": "https://images.unsplash.com/photo-1510619586150-1376d29944a1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Países Baixos",
    "cidade": "Haia",
    "instituicaoResponsavel": "Haia Academy of International Law",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 1 ano focado em direito internacional público e privado. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria de tecnologia.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 100+) ou Francês (B2+)",
    "requisitosEspecificos": "Graduação em direito ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "1 ano",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da academia.",
    "linkOficial": "https://www.hague-academy.nl/english/law-programs",
    "contato": "master-admissions@hague-academy.nl"
  },
  {
    "id": 37,
    "nome": "Curso de Verão em Fotografia em Paris",
    "imagem": "https://images.unsplash.com/photo-1512496011470-76133be929d2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "França",
    "cidade": "Paris",
    "instituicaoResponsavel": "Escola de Fotografia de Paris",
    "tipo": "Curso de verão",
    "descricao": "Duas semanas de imersão em fotografia, com aulas teóricas e saídas práticas pela cidade. Foco em fotografia de rua e paisagem.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Francês (B1) ou Inglês (B2)",
    "requisitosEspecificos": "Portfólio de 5 a 10 fotos.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "2 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.paris-photography-school.fr/summer-photography",
    "contato": "info@paris-photography-school.fr"
  },
  {
    "id": 38,
    "nome": "Estágio em Relações Públicas em Londres",
    "imagem": "https://images.unsplash.com/photo-1528695027581-229418641974?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Reino Unido",
    "cidade": "Londres",
    "instituicaoResponsavel": "Agência de Relações Públicas",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de relações públicas, com foco em comunicação e marketing digital. Oportunidade de trabalhar em uma agência de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1)",
    "requisitosEspecificos": "Estar cursando relações públicas ou marketing.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e portfólio, entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a agência.",
    "linkOficial": "https://www.pr-agency.co.uk/internship",
    "contato": "internships@pr-agency.co.uk"
  },
  {
    "id": 39,
    "nome": "Bolsa de Mestrado em Engenharia Aeroespacial",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Alemanha",
    "cidade": "Berlim",
    "instituicaoResponsavel": "Universidade Técnica de Berlim",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em engenharia aeroespacial e sistemas espaciais. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Graduação em engenharia, ciência da computação ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da universidade.",
    "linkOficial": "https://www.tu-berlin.de/en/master/aerospace-engineering",
    "contato": "master-admissions@tu-berlin.de"
  },
  {
    "id": 40,
    "nome": "Curso de Verão em Moda em Milão",
    "imagem": "https://images.unsplash.com/photo-1512496011470-76133be929d2?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Itália",
    "cidade": "Milão",
    "instituicaoResponsavel": "Istituto Marangoni",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em design de moda, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Italiano (B2) ou Inglês (B2)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de arte.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.istitutomarangoni.com/en/short-courses/fashion-design-milano",
    "contato": "info@istitutomarangoni.com"
  },
  {
    "id": 41,
    "nome": "Estágio em Finanças em Zurique",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Suíça",
    "cidade": "Zurique",
    "instituicaoResponsavel": "Banco de Investimento Global",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de finanças, com foco em análise de mercado e gestão de portfólio. Oportunidade de trabalhar em um banco de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1) e Alemão (B1)",
    "requisitosEspecificos": "Estar cursando finanças, economia ou áreas correlatas.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo, teste de habilidades e entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para o banco.",
    "linkOficial": "https://www.global-bank.ch/internship",
    "contato": "internships@global-bank.ch"
  },
  {
    "id": 42,
    "nome": "Bolsa de Mestrado em Engenharia Biomédica",
    "imagem": "https://images.unsplash.com/photo-1510619586150-1376d29944a1?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Suécia",
    "cidade": "Estocolmo",
    "instituicaoResponsavel": "KTH Royal Institute of Technology",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em engenharia biomédica e tecnologias de saúde. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Graduação em engenharia, biologia ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da universidade.",
    "linkOficial": "https://www.kth.se/en/master/biomedical-engineering",
    "contato": "master-admissions@kth.se"
  },
  {
    "id": 43,
    "nome": "Curso de Verão em Design Gráfico em Londres",
    "imagem": "https://images.unsplash.com/photo-1522881267597-1521d9607f20?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Reino Unido",
    "cidade": "Londres",
    "instituicaoResponsavel": "Central Saint Martins",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em design gráfico, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 6.5+)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de arte.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.arts.ac.uk/csm/courses/short-courses/graphic-design-summer-school",
    "contato": "shortcourses@csm.arts.ac.uk"
  },
  {
    "id": 44,
    "nome": "Estágio em Jornalismo em Nova York",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Estados Unidos",
    "cidade": "Nova York",
    "instituicaoResponsavel": "Agência de Notícias Global",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de jornalismo, com foco em reportagem e produção de conteúdo digital. Oportunidade de trabalhar em uma agência de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1)",
    "requisitosEspecificos": "Estar cursando jornalismo ou comunicação, portfólio de artigos publicados.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e portfólio, entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a agência.",
    "linkOficial": "https://www.global-news.com/internship",
    "contato": "internships@global-news.com"
  },
  {
    "id": 45,
    "nome": "Bolsa de Mestrado em Engenharia Civil",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Canadá",
    "cidade": "Vancouver",
    "instituicaoResponsavel": "Universidade da Colúmbia Britânica (UBC)",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em engenharia civil e gestão de projetos. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+)",
    "requisitosEspecificos": "Graduação em engenharia civil ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da universidade.",
    "linkOficial": "https://www.civil.ubc.ca/graduate/programs",
    "contato": "graduate-admissions@civil.ubc.ca"
  },
  {
    "id": 46,
    "nome": "Curso de Verão em Teatro em Londres",
    "imagem": "https://images.unsplash.com/photo-1522881267597-1521d9607f20?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Reino Unido",
    "cidade": "Londres",
    "instituicaoResponsavel": "Royal Academy of Dramatic Art (RADA)",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em teatro, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 6.5+)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de arte.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da escola.",
    "linkOficial": "https://www.rada.ac.uk/short-courses/summer-shakespeare-course",
    "contato": "shortcourses@rada.ac.uk"
  },
  {
    "id": 47,
    "nome": "Estágio em Marketing em Hong Kong",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Hong Kong",
    "cidade": "Hong Kong",
    "instituicaoResponsavel": "Agência de Marketing Global",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de marketing, com foco em comunicação e marketing digital. Oportunidade de trabalhar em uma agência de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1) e Cantonês (B1)",
    "requisitosEspecificos": "Estar cursando marketing ou comunicação.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo e portfólio, entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a agência.",
    "linkOficial": "https://www.global-marketing.hk/internship",
    "contato": "internships@global-marketing.hk"
  },
  {
    "id": 48,
    "nome": "Bolsa de Mestrado em Engenharia Elétrica",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Japão",
    "cidade": "Osaka",
    "instituicaoResponsavel": "Universidade de Osaka",
    "tipo": "Mestrado",
    "descricao": "Mestrado de 2 anos focado em engenharia elétrica e eletrônica. Oportunidade de trabalhar em projetos de pesquisa e ter contato com a indústria.",
    "nivelEnsino": "Mestrado",
    "faixaEtaria": "Sem restrição",
    "requisitosIdioma": "Inglês (TOEFL iBT 90+) ou Japonês (JLPT N2+)",
    "requisitosEspecificos": "Graduação em engenharia elétrica ou áreas correlatas.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Taxa de matrícula completa e uma mesada para despesas de moradia e alimentação.",
    "custosExtras": "Passagem aérea e seguro.",
    "duracao": "2 anos",
    "prazoInscricao": "15/01/2026",
    "etapasSelecao": "Análise documental e entrevista online.",
    "processoInscricao": "Plataforma de candidatura online da universidade.",
    "linkOficial": "https://www.osaka-u.ac.jp/en/admissions/graduate/electrical-engineering",
    "contato": "master-admissions@osaka-u.ac.jp"
  },
  {
    "id": 49,
    "nome": "Curso de Verão em Escrita Criativa",
    "imagem": "https://images.unsplash.com/photo-1522881267597-1521d9607f20?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Irlanda",
    "cidade": "Dublin",
    "instituicaoResponsavel": "Trinity College Dublin",
    "tipo": "Curso de verão",
    "descricao": "Três semanas de imersão em escrita criativa, com aulas teóricas e práticas, visitas a estúdios e museus. Ideal para estudantes que desejam aprofundar seus conhecimentos.",
    "nivelEnsino": "Graduação",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (IELTS 7.0+)",
    "requisitosEspecificos": "Portfólio de 5 a 10 peças de escrita.",
    "taxaAplicacao": "Pago",
    "tipoBolsa": "Parcial",
    "coberturaBolsa": "Cobre até 50% da taxa de matrícula para os alunos com melhor portfólio.",
    "custosExtras": "Taxa de matrícula (parcial), passagem, hospedagem, alimentação e seguro.",
    "duracao": "3 semanas",
    "prazoInscricao": "30/04/2026",
    "etapasSelecao": "Análise de portfólio.",
    "processoInscricao": "Inscrição online no site da universidade.",
    "linkOficial": "https://www.tcd.ie/summer-school-creative-writing",
    "contato": "summerschool@tcd.ie"
  },
  {
    "id": 50,
    "nome": "Estágio em Direitos Humanos em Genebra",
    "imagem": "https://images.unsplash.com/photo-1549721092-23f4b50c0071?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "pais": "Suíça",
    "cidade": "Genebra",
    "instituicaoResponsavel": "Alto Comissariado das Nações Unidas para os Direitos Humanos (ACNUDH)",
    "tipo": "Estágio/Trabalho",
    "descricao": "Estágio de 6 meses para estudantes de direito ou relações internacionais, com foco em direitos humanos e diplomacia. Oportunidade de trabalhar em uma agência de renome mundial.",
    "nivelEnsino": "Graduação, Mestrado",
    "faixaEtaria": "18+",
    "requisitosIdioma": "Inglês (C1) e Francês (C1)",
    "requisitosEspecificos": "Estar cursando direito ou relações internacionais.",
    "taxaAplicacao": "Gratuito",
    "tipoBolsa": "Completa",
    "coberturaBolsa": "Salário mensal, visto e seguro.",
    "custosExtras": "Passagem aérea, hospedagem e alimentação.",
    "duracao": "6 meses",
    "prazoInscricao": "01/03/2026",
    "etapasSelecao": "Análise de currículo, teste de habilidades e entrevista online.",
    "processoInscricao": "Envio de currículo e documentos por e-mail para a agência.",
    "linkOficial": "https://www.ohchr.org/en/about-us/careers/internships",
    "contato": "internships@ohchr.org"
  }
]