export const oportunidadesInternacionais = [
    {
        id: 101,
        nome: "Summer School de IA Aplicada",
        imagem:
            "https://images.unsplash.com/photo-1518773553398-650c184e0bb3?q=80&w=1974&auto=format&fit=crop",
        pais: "Estados Unidos",
        cidade: "San Francisco",
        instituicaoResponsavel: "Westbridge Institute of Technology",
        tipo: "Curso de verão",
        descricao:
            "Programa intensivo com foco em machine learning aplicado a produtos reais, com laboratorios e mentoria internacional.",
        nivelEnsino: "Graduação",
        faixaEtaria: "18-30",
        requisitosIdioma: "Inglês (B2)",
        requisitosEspecificos: "Conhecimento basico de programacao em Python.",
        taxaAplicacao: "Pago",
        tipoBolsa: "Parcial",
        coberturaBolsa: "Desconto de 60% na tuition para candidatos selecionados.",
        custosExtras: "Hospedagem, alimentacao e transporte local.",
        duracao: "4 semanas",
        prazoInscricao: "30/06/2026",
        etapasSelecao: "Formulario, carta de motivacao e entrevista.",
        processoInscricao: "Inscricao online pela plataforma oficial.",
        linkOficial: "https://example.org/intl/ai-summer-school",
        contato: "admissions@westbridge.example.org",
    },
    {
        id: 102,
        nome: "Intercambio de Impacto Social",
        imagem:
            "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=2071&auto=format&fit=crop",
        pais: "Canadá",
        cidade: "Toronto",
        instituicaoResponsavel: "Global Civic Lab",
        tipo: "Intercâmbio cultural",
        descricao:
            "Vivencia em projetos comunitarios com equipes multiculturais e oficinas de lideranca para jovens agentes de mudanca.",
        nivelEnsino: "Graduação",
        faixaEtaria: "18-26",
        requisitosIdioma: "Inglês (B2)",
        requisitosEspecificos: "Experiencia previa em voluntariado e carta de recomendacao.",
        taxaAplicacao: "Gratuito",
        tipoBolsa: "Completa",
        coberturaBolsa: "Passagem, acomodacao, seguro e ajuda de custo.",
        custosExtras: "Despesas pessoais.",
        duracao: "10 semanas",
        prazoInscricao: "20/07/2026",
        etapasSelecao: "Analise documental e dinamica em grupo online.",
        processoInscricao: "Preenchimento de formulario e envio de video.",
        linkOficial: "https://example.org/intl/social-impact",
        contato: "selection@globalcivic.example.org",
    },
    {
        id: 103,
        nome: "Mestrado em Cidades Sustentáveis",
        imagem:
            "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=2070&auto=format&fit=crop",
        pais: "Países Baixos",
        cidade: "Roterdã",
        instituicaoResponsavel: "European Urban School",
        tipo: "Mestrado",
        descricao:
            "Programa de dois anos sobre planejamento urbano, mobilidade e transicao energetica com projetos em cidades europeias.",
        nivelEnsino: "Mestrado",
        faixaEtaria: "Sem restrição",
        requisitosIdioma: "Inglês (C1)",
        requisitosEspecificos: "Diploma de graduacao em areas correlatas.",
        taxaAplicacao: "Pago",
        tipoBolsa: "Completa",
        coberturaBolsa: "Tuition integral e bolsa mensal de manutencao.",
        custosExtras: "Passagem inicial e taxa de visto.",
        duracao: "2 anos",
        prazoInscricao: "10/08/2026",
        etapasSelecao: "Analise de historico, projeto e entrevista.",
        processoInscricao: "Portal de admissions da instituicao.",
        linkOficial: "https://example.org/intl/sustainable-cities",
        contato: "masters@eus.example.org",
    },
    {
        id: 104,
        nome: "Fellowship em Jornalismo de Dados",
        imagem:
            "https://images.unsplash.com/photo-1495020689067-958852a7765e?q=80&w=1974&auto=format&fit=crop",
        pais: "Reino Unido",
        cidade: "Londres",
        instituicaoResponsavel: "Open Media Fellowship",
        tipo: "Pesquisa",
        descricao:
            "Formacao pratica em investigacao orientada a dados, visualizacao e storytelling para impacto publico.",
        nivelEnsino: "Pós-Doutorado",
        faixaEtaria: "24+",
        requisitosIdioma: "Inglês (C1)",
        requisitosEspecificos: "Portfolio com reportagens analiticas publicadas.",
        taxaAplicacao: "Gratuito",
        tipoBolsa: "Parcial",
        coberturaBolsa: "Stipend mensal e acesso a laboratorios de dados.",
        custosExtras: "Moradia e alimentacao.",
        duracao: "9 meses",
        prazoInscricao: "15/09/2026",
        etapasSelecao: "Triagem tecnica, case e entrevista final.",
        processoInscricao: "Submissao de portfolio e formulario online.",
        linkOficial: "https://example.org/intl/data-journalism-fellowship",
        contato: "fellows@openmedia.example.org",
    },
    {
        id: 105,
        nome: "Programa de Inverno em Empreendedorismo",
        imagem:
            "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop",
        pais: "Finlândia",
        cidade: "Helsinque",
        instituicaoResponsavel: "Nordic Startup Academy",
        tipo: "Evento/Workshop",
        descricao:
            "Bootcamp com desafios reais de startups, mentorias e pitch day com investidores.",
        nivelEnsino: "Graduação",
        faixaEtaria: "18+",
        requisitosIdioma: "Inglês (B2)",
        requisitosEspecificos: "Equipe de 2 a 4 pessoas com ideia validada.",
        taxaAplicacao: "Pago",
        tipoBolsa: "Sem bolsa",
        coberturaBolsa: "Não aplicável.",
        custosExtras: "Passagem, hospedagem e alimentacao.",
        duracao: "2 semanas",
        prazoInscricao: "05/10/2026",
        etapasSelecao: "Analise de proposta e entrevista curta.",
        processoInscricao: "Aplicacao via formulario oficial.",
        linkOficial: "https://example.org/intl/winter-entrepreneurship",
        contato: "apply@nordicstartup.example.org",
    },
    {
        id: 106,
        nome: "High School Exchange em Kyoto",
        imagem:
            "https://images.unsplash.com/photo-1492571350019-22de08371fd3?q=80&w=2070&auto=format&fit=crop",
        pais: "Japão",
        cidade: "Kyoto",
        instituicaoResponsavel: "East Bridges Exchange",
        tipo: "High School",
        descricao:
            "Ano letivo em escola japonesa com familia anfitria, aulas de idioma e atividades culturais.",
        nivelEnsino: "Ensino Médio",
        faixaEtaria: "15-17",
        requisitosIdioma: "Inglês (B1)",
        requisitosEspecificos: "Bom desempenho escolar e entrevista com responsaveis.",
        taxaAplicacao: "Gratuito",
        tipoBolsa: "Completa",
        coberturaBolsa: "Matricula, hospedagem, seguro e apoio local.",
        custosExtras: "Passagem e despesas pessoais.",
        duracao: "10 meses",
        prazoInscricao: "01/11/2026",
        etapasSelecao: "Analise de boletim, entrevista e perfil cultural.",
        processoInscricao: "Candidatura online e envio de documentos.",
        linkOficial: "https://example.org/intl/kyoto-highschool",
        contato: "intake@eastbridges.example.org",
    },
    {
        id: 107,
        nome: "Estágio em Relações Internacionais",
        imagem:
            "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2070&auto=format&fit=crop",
        pais: "Suíça",
        cidade: "Genebra",
        instituicaoResponsavel: "Global Diplomacy Center",
        tipo: "Estágio/Trabalho",
        descricao:
            "Atuacao em projetos multilaterais com acompanhamento de negociacoes e elaboracao de briefs.",
        nivelEnsino: "Graduação",
        faixaEtaria: "20+",
        requisitosIdioma: "Inglês (C1) e Francês (B2)",
        requisitosEspecificos: "Matricula ativa em RI, Direito ou Economia.",
        taxaAplicacao: "Gratuito",
        tipoBolsa: "Parcial",
        coberturaBolsa: "Bolsa mensal de apoio transporte e alimentacao.",
        custosExtras: "Moradia e visto.",
        duracao: "6 meses",
        prazoInscricao: "12/11/2026",
        etapasSelecao: "Triagem, teste escrito e painel de entrevista.",
        processoInscricao: "Portal de carreiras da instituicao.",
        linkOficial: "https://example.org/intl/diplomacy-internship",
        contato: "careers@gdc.example.org",
    },
    {
        id: 108,
        nome: "Doutorado em Energia Limpa",
        imagem:
            "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=2069&auto=format&fit=crop",
        pais: "Alemanha",
        cidade: "Munique",
        instituicaoResponsavel: "Institute for Clean Tech",
        tipo: "Doutorado",
        descricao:
            "Pesquisa aplicada em armazenamento energetico com parcerias industriais e laboratorios de ponta.",
        nivelEnsino: "Doutorado",
        faixaEtaria: "Sem restrição",
        requisitosIdioma: "Inglês (C1)",
        requisitosEspecificos: "Mestrado em engenharia, fisica ou quimica.",
        taxaAplicacao: "Gratuito",
        tipoBolsa: "Completa",
        coberturaBolsa: "Taxas academicas, bolsa mensal e seguro.",
        custosExtras: "Custos de mudanca inicial.",
        duracao: "4 anos",
        prazoInscricao: "30/11/2026",
        etapasSelecao: "Projeto de pesquisa, entrevista e avaliacao tecnica.",
        processoInscricao: "Envio de proposta e documentos pela plataforma.",
        linkOficial: "https://example.org/intl/phd-clean-energy",
        contato: "phd@cleantech.example.org",
    },
    {
        id: 109,
        nome: "Voluntariado em Educação Comunitária",
        imagem:
            "https://images.unsplash.com/photo-1469571486292-b53601020fa5?q=80&w=2070&auto=format&fit=crop",
        pais: "Costa Rica",
        cidade: "San José",
        instituicaoResponsavel: "Bright Communities Network",
        tipo: "Trabalho voluntário",
        descricao:
            "Apoio a projetos de alfabetizacao e reforco escolar em comunidades vulneraveis.",
        nivelEnsino: "Ensino Médio",
        faixaEtaria: "16+",
        requisitosIdioma: "Espanhol (B1)",
        requisitosEspecificos: "Disponibilidade para trabalho em campo.",
        taxaAplicacao: "Pago",
        tipoBolsa: "Sem bolsa",
        coberturaBolsa: "Não aplicável.",
        custosExtras: "Taxa do programa, passagem e seguro.",
        duracao: "6 semanas",
        prazoInscricao: "15/12/2026",
        etapasSelecao: "Formulario e entrevista de alinhamento.",
        processoInscricao: "Inscricao online e envio de comprovantes.",
        linkOficial: "https://example.org/intl/community-education",
        contato: "programs@brightcommunities.example.org",
    },
    {
        id: 110,
        nome: "Curso Intensivo de Negócios Globais",
        imagem:
            "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2070&auto=format&fit=crop",
        pais: "Singapura",
        cidade: "Singapura",
        instituicaoResponsavel: "Asia Global Business School",
        tipo: "Curso curta duração",
        descricao:
            "Capacitacao em estrategia internacional, negociacao e mercados asiaticos com professores convidados.",
        nivelEnsino: "MBA",
        faixaEtaria: "23+",
        requisitosIdioma: "Inglês (C1)",
        requisitosEspecificos: "Experiencia profissional minima de 2 anos.",
        taxaAplicacao: "Pago",
        tipoBolsa: "Parcial",
        coberturaBolsa: "Bolsa de 40% para perfis de alta performance.",
        custosExtras: "Hospedagem e transporte local.",
        duracao: "5 semanas",
        prazoInscricao: "20/12/2026",
        etapasSelecao: "Formulario, CV e entrevista.",
        processoInscricao: "Aplicacao no portal oficial.",
        linkOficial: "https://example.org/intl/global-business",
        contato: "admissions@agbs.example.org",
    },
]
