export const oportunidadesNacionais = [
  {
    id: 1,
    nome: "Jovens Lideranças da Amazônia",
    imagem:
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Programas de Liderança",
    nivelEnsino: "Ensino Médio",
    modalidade: "Presencial",
    prazoInscricao: "25/05/2026",
    sobre:
      "Formacao de liderancas socioambientais para juventudes da regiao Norte.",
    descricaoBreve:
      "Programa com trilhas de lideranca, sustentabilidade e comunicacao para impacto local.",
    duracao: "5 meses",
    cidadeEstado: "Manaus/AM",
    faixaEtaria: "15-19",
    requisitos: "Estar matriculado no ensino medio e residir na regiao Norte.",
    requisitosEspecificos: [
      "Carta de motivacao",
      "Disponibilidade para encontros quinzenais",
      "Participacao em projeto comunitario",
    ],
    instituicaoResponsavel: "Instituto Floresta Viva",
    taxaAplicacao: "Gratuito",
    beneficios:
      "Formacao completa, mentoria, transporte local e certificado final.",
    custos: "Não há custos obrigatorios para participantes selecionados.",
    custosExtras: "Despesas pessoais.",
    etapasSelecao: "Inscricao, analise de perfil e entrevista online.",
    linkOficial: "https://example.org/nacional/liderancas-amazonia",
    contato: "selecoes@florestaviva.example.org",
  },
  {
    id: 2,
    nome: "Feira Nacional de Ciências Aplicadas",
    imagem:
      "https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Feiras de Ciências",
    nivelEnsino: "Ensino Médio",
    modalidade: "Presencial",
    prazoInscricao: "10/06/2026",
    sobre:
      "Mostra nacional de projetos de ciencia, tecnologia e inovacao estudantil.",
    descricaoBreve:
      "Evento para estudantes apresentarem pesquisas com banca avaliadora e premiacao.",
    duracao: "4 dias",
    cidadeEstado: "Recife/PE",
    faixaEtaria: "14-20",
    requisitos:
      "Projeto cientifico original validado por professor orientador.",
    requisitosEspecificos: [
      "Resumo expandido",
      "Video de apresentacao de ate 3 minutos",
      "Termo de autorizacao da escola",
    ],
    instituicaoResponsavel: "Rede Brasileira de Feiras Cientificas",
    taxaAplicacao: "Gratuito",
    beneficios:
      "Acesso a laboratorios parceiros, certificacao e networking academico.",
    custos: "Inscricao gratuita para todos os aprovados.",
    custosExtras: "Transporte e hospedagem para delegacoes.",
    etapasSelecao:
      "Triagem documental, avaliacao tecnica e classificacao final.",
    linkOficial: "https://example.org/nacional/feira-ciencias-aplicadas",
    contato: "contato@rbfc.example.org",
  },
  {
    id: 3,
    nome: "Mentoria ENEM 360",
    imagem:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Programas de Mentoria",
    nivelEnsino: "Ensino Médio",
    modalidade: "Online",
    prazoInscricao: "01/07/2026",
    sobre:
      "Mentoria nacional para estudantes de escola publica focada no ENEM.",
    descricaoBreve:
      "Acompanhamento semanal com mentores universitarios e plano individual de estudos.",
    duracao: "6 meses",
    cidadeEstado: "Online",
    faixaEtaria: "16-21",
    requisitos: "Estar no 2o ou 3o ano do ensino medio ou egresso recente.",
    requisitosEspecificos: [
      "Comprovante escolar",
      "Questionario socioeducacional",
      "Compromisso de participacao semanal",
    ],
    instituicaoResponsavel: "Plataforma Ponte para Universidade",
    taxaAplicacao: "Gratuito",
    beneficios: "Aulas ao vivo, simulados, monitorias e trilha socioemocional.",
    custos: "Sem custos.",
    custosExtras: "Internet e equipamentos para acesso online.",
    etapasSelecao: "Formulario, prova diagnostica e entrevista.",
    linkOficial: "https://example.org/nacional/mentoria-enem-360",
    contato: "apoio@ponteuniversidade.example.org",
  },
  {
    id: 4,
    nome: "Iniciação Científica Júnior em Saúde",
    imagem:
      "https://images.unsplash.com/photo-1579165466741-7f35e4755660?q=80&w=1974&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Iniciação Científica",
    nivelEnsino: "Ensino Médio",
    modalidade: "Presencial",
    prazoInscricao: "15/07/2026",
    sobre:
      "Projeto de iniciacao cientifica em laboratorios universitarios de saude.",
    descricaoBreve:
      "Estudantes desenvolvem pesquisa orientada por docentes e apresentam em congresso estudantil.",
    duracao: "8 meses",
    cidadeEstado: "Belo Horizonte/MG",
    faixaEtaria: "15-19",
    requisitos:
      "Interesse em ciencias da saude e disponibilidade no contraturno.",
    requisitosEspecificos: [
      "Historico escolar",
      "Carta de interesse",
      "Autorizacao dos responsaveis",
    ],
    instituicaoResponsavel: "Universidade Aberta para Jovens Pesquisadores",
    taxaAplicacao: "Gratuito",
    beneficios:
      "Bolsa mensal, acesso a laboratorios e orientacao especializada.",
    custos: "Sem custos para participantes bolsistas.",
    custosExtras: "Transporte urbano e refeicoes extras.",
    etapasSelecao: "Analise documental, prova de ciencias e entrevista.",
    linkOficial: "https://example.org/nacional/icj-saude",
    contato: "icj@uajp.example.org",
  },
  {
    id: 5,
    nome: "Simulação Nacional da ONU Jovem",
    imagem:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Simulações da ONU",
    nivelEnsino: "Graduação",
    modalidade: "Presencial",
    prazoInscricao: "30/07/2026",
    sobre: "Conferencia academica que simula comites internacionais da ONU.",
    descricaoBreve:
      "Experiencia de diplomacia, negociacao e redacao de resolucoes para estudantes.",
    duracao: "5 dias",
    cidadeEstado: "Brasília/DF",
    faixaEtaria: "17-26",
    requisitos: "Interesse em politica internacional e debate.",
    requisitosEspecificos: [
      "Formulario completo",
      "Mini position paper",
      "Participacao em oficina preparatoria",
    ],
    instituicaoResponsavel: "Forum Brasileiro de Diplomacia Jovem",
    taxaAplicacao: "Pago",
    beneficios:
      "Treinamentos previos, certificacao e acesso a rede de ex-alunos.",
    custos: "Taxa unica de participacao para materiais e infraestrutura.",
    custosExtras: "Hospedagem, transporte e alimentacao.",
    etapasSelecao:
      "Inscricao, avaliacao de position paper e alocacao de comite.",
    linkOficial: "https://example.org/nacional/simulacao-onu-jovem",
    contato: "secretariat@fbdj.example.org",
  },
  {
    id: 6,
    nome: "Imersão em Tecnologia Criativa",
    imagem:
      "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Cursos & Imersões",
    nivelEnsino: "Graduação",
    modalidade: "Online",
    prazoInscricao: "05/08/2026",
    sobre: "Imersao em design digital, UX e prototipagem de produtos.",
    descricaoBreve:
      "Curso pratico com desafios semanais e mentorias ao vivo com especialistas de mercado.",
    duracao: "12 semanas",
    cidadeEstado: "Online",
    faixaEtaria: "18+",
    requisitos: "Conhecimentos basicos de ferramentas digitais.",
    requisitosEspecificos: [
      "Portifolio inicial (opcional)",
      "Computador com acesso a internet",
      "Disponibilidade para encontros noturnos",
    ],
    instituicaoResponsavel: "Lab Criativo Brasil",
    taxaAplicacao: "Pago",
    beneficios: "Mentorias, comunidade exclusiva e certificado de conclusao.",
    custos: "Mensalidade com possibilidade de bolsa social parcial.",
    custosExtras: "Assinaturas de software (quando necessario).",
    etapasSelecao: "Formulario, desafio rapido e entrevista de fit.",
    linkOficial: "https://example.org/nacional/imersao-tech-criativa",
    contato: "admissao@labcriativo.example.org",
  },
  {
    id: 7,
    nome: "Olimpíada Nacional de Dados e IA",
    imagem:
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Olimpíadas",
    nivelEnsino: "Ensino Médio",
    modalidade: "Online",
    prazoInscricao: "12/08/2026",
    sobre:
      "Competicao nacional para jovens talentos em dados, estatistica e IA.",
    descricaoBreve:
      "Desafios em fases com ranking nacional e trilhas de estudo recomendadas.",
    duracao: "3 meses",
    cidadeEstado: "Online",
    faixaEtaria: "14-20",
    requisitos: "Conhecimentos basicos de matematica e logica.",
    requisitosEspecificos: [
      "Cadastro individual",
      "Termo de consentimento",
      "Realizacao da fase classificatoria",
    ],
    instituicaoResponsavel: "Liga Brasileira de Ciencia de Dados",
    taxaAplicacao: "Gratuito",
    beneficios:
      "Medalhas, mentorias com especialistas e vagas em programa de talentos.",
    custos: "Sem custos.",
    custosExtras: "Internet para participacao nas fases online.",
    etapasSelecao: "Fase 1 objetiva, Fase 2 pratica e final ao vivo.",
    linkOficial: "https://example.org/nacional/olimpiada-dados-ia",
    contato: "suporte@lbcd.example.org",
  },
  {
    id: 8,
    nome: "Programa Social de Inovação Local",
    imagem:
      "https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Voluntariado/Social",
    nivelEnsino: "Graduação",
    modalidade: "Presencial",
    prazoInscricao: "22/08/2026",
    sobre:
      "Projeto colaborativo para desenvolvimento de solucoes comunitarias.",
    descricaoBreve:
      "Times multidisciplinares cocriam propostas para desafios de territórios urbanos.",
    duracao: "4 meses",
    cidadeEstado: "Salvador/BA",
    faixaEtaria: "18-29",
    requisitos: "Interesse em impacto social e trabalho em equipe.",
    requisitosEspecificos: [
      "Formulario de candidatura",
      "Disponibilidade para encontros presenciais",
      "Participacao em oficina inicial",
    ],
    instituicaoResponsavel: "Rede Nacional de Inovacao Social",
    taxaAplicacao: "Gratuito",
    beneficios: "Formacao pratica, mentorias e certificacao por projeto.",
    custos: "Sem taxa de inscricao.",
    custosExtras: "Transporte para atividades presenciais.",
    etapasSelecao: "Inscricao, entrevista em grupo e formacao de equipes.",
    linkOficial: "https://example.org/nacional/inovacao-local",
    contato: "programa@rnis.example.org",
  },
  {
    id: 9,
    nome: "Laboratório de Carreiras STEM",
    imagem:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Programas de Mentoria",
    nivelEnsino: "Graduação",
    modalidade: "Online",
    prazoInscricao: "30/08/2026",
    sobre:
      "Aceleracao de carreira para estudantes de STEM com trilhas praticas.",
    descricaoBreve:
      "Mentoria de carreira, simulacao de entrevistas e desenvolvimento de portfolio tecnico.",
    duracao: "16 semanas",
    cidadeEstado: "Online",
    faixaEtaria: "18+",
    requisitos: "Ser estudante ativo de curso superior em STEM.",
    requisitosEspecificos: [
      "Curriculo atualizado",
      "Carta de objetivos",
      "Compromisso com encontros semanais",
    ],
    instituicaoResponsavel: "Hub Nacional de Talentos STEM",
    taxaAplicacao: "Pago",
    beneficios: "Mentoria individual, networking com empresas e certificado.",
    custos: "Taxa de participacao com bolsas parciais para baixa renda.",
    custosExtras: "Eventuais custos de deslocamento para encontros opcionais.",
    etapasSelecao: "Triagem de perfil e entrevista com mentores.",
    linkOficial: "https://example.org/nacional/lab-carreiras-stem",
    contato: "team@hubstem.example.org",
  },
  {
    id: 10,
    nome: "Desafio Nacional de Soluções Climáticas",
    imagem:
      "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?q=80&w=2070&auto=format&fit=crop",
    pais: "Brasil",
    tipo: "Feiras de Ciências",
    nivelEnsino: "Ensino Médio",
    modalidade: "Presencial",
    prazoInscricao: "10/09/2026",
    sobre:
      "Competicao para desenvolver prototipos de mitigacao e adaptacao climatica.",
    descricaoBreve:
      "Equipes apresentam solucoes sustentaveis para banca de especialistas e investidores sociais.",
    duracao: "6 semanas",
    cidadeEstado: "Curitiba/PR",
    faixaEtaria: "15-22",
    requisitos: "Equipe de ate 4 integrantes e orientador responsavel.",
    requisitosEspecificos: [
      "Projeto com viabilidade tecnica",
      "Pitch deck",
      "Video demonstracao do prototipo",
    ],
    instituicaoResponsavel: "Coalizao Clima Jovem",
    taxaAplicacao: "Gratuito",
    beneficios: "Premiacao, incubacao de projetos e mentoria especializada.",
    custos: "Nao ha taxa de inscricao.",
    custosExtras: "Custos de prototipagem e deslocamento.",
    etapasSelecao: "Inscricao, semifinal online e final presencial.",
    linkOficial: "https://example.org/nacional/desafio-climatico",
    contato: "edital@climajovem.example.org",
  },
]
